/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten.  Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0
* @since   2017-01-03
*
* A class which represents the NameOf class - this is used to get the json field names of
* SugarCRM Pojo classes .
*/

package com.sugaronrest;

public class NameOf {
    public static class Accounts {
        public static String SugarModuleName = "accounts";
        public static String Id = "id";
        public static String Name = "name";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String AccountType = "account_type";
        public static String Industry = "industry";
        public static String AnnualRevenue = "annual_revenue";
        public static String PhoneFax = "phone_fax";
        public static String BillingAddressStreet = "billing_address_street";
        public static String BillingAddressCity = "billing_address_city";
        public static String BillingAddressState = "billing_address_state";
        public static String BillingAddressPostalcode = "billing_address_postalcode";
        public static String BillingAddressCountry = "billing_address_country";
        public static String Rating = "rating";
        public static String PhoneOffice = "phone_office";
        public static String PhoneAlternate = "phone_alternate";
        public static String Website = "website";
        public static String Ownership = "ownership";
        public static String Employees = "employees";
        public static String TickerSymbol = "ticker_symbol";
        public static String ShippingAddressStreet = "shipping_address_street";
        public static String ShippingAddressCity = "shipping_address_city";
        public static String ShippingAddressState = "shipping_address_state";
        public static String ShippingAddressPostalcode = "shipping_address_postalcode";
        public static String ShippingAddressCountry = "shipping_address_country";
        public static String ParentId = "parent_id";
        public static String SicCode = "sic_code";
        public static String CampaignId = "campaign_id";
    }

    public static class AccountsAudit {
        public static String SugarModuleName = "accounts_audit";
        public static String Id = "id";
        public static String ParentId = "parent_id";
        public static String DateCreated = "date_created";
        public static String CreatedBy = "created_by";
        public static String FieldName = "field_name";
        public static String DataType = "data_type";
        public static String BeforeValueString = "before_value_string";
        public static String AfterValueString = "after_value_string";
        public static String BeforeValueText = "before_value_text";
        public static String AfterValueText = "after_value_text";
    }

    public static class AccountsBugs {
        public static String SugarModuleName = "accounts_bugs";
        public static String Id = "id";
        public static String AccountId = "account_id";
        public static String BugId = "bug_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class AccountsCases {
        public static String SugarModuleName = "accounts_cases";
        public static String Id = "id";
        public static String AccountId = "account_id";
        public static String CaseId = "case_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class AccountsContacts {
        public static String SugarModuleName = "accounts_contacts";
        public static String Id = "id";
        public static String ContactId = "contact_id";
        public static String AccountId = "account_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class AccountsOpportunities {
        public static String SugarModuleName = "accounts_opportunities";
        public static String Id = "id";
        public static String OpportunityId = "opportunity_id";
        public static String AccountId = "account_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class AclActions {
        public static String SugarModuleName = "acl_actions";
        public static String Id = "id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Name = "name";
        public static String Category = "category";
        public static String Acltype = "acltype";
        public static String Aclaccess = "aclaccess";
        public static String Deleted = "deleted";
    }

    public static class AclRoles {
        public static String SugarModuleName = "acl_roles";
        public static String Id = "id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Name = "name";
        public static String Description = "description";
        public static String Deleted = "deleted";
    }

    public static class AclRolesActions {
        public static String SugarModuleName = "acl_roles_actions";
        public static String Id = "id";
        public static String RoleId = "role_id";
        public static String ActionId = "action_id";
        public static String AccessOverride = "access_override";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class AclRolesUsers {
        public static String SugarModuleName = "acl_roles_users";
        public static String Id = "id";
        public static String RoleId = "role_id";
        public static String UserId = "user_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class AddressBook {
        public static String SugarModuleName = "address_book";
        public static String AssignedUserId = "assigned_user_id";
        public static String Bean = "bean";
        public static String BeanId = "bean_id";
    }

    public static class Bugs {
        public static String SugarModuleName = "bugs";
        public static String Id = "id";
        public static String Name = "name";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String BugNumber = "bug_number";
        public static String Type = "type";
        public static String Status = "status";
        public static String Priority = "priority";
        public static String Resolution = "resolution";
        public static String WorkLog = "work_log";
        public static String FoundInRelease = "found_in_release";
        public static String FixedInRelease = "fixed_in_release";
        public static String Source = "source";
        public static String ProductCategory = "product_category";
    }

    public static class BugsAudit {
        public static String SugarModuleName = "bugs_audit";
        public static String Id = "id";
        public static String ParentId = "parent_id";
        public static String DateCreated = "date_created";
        public static String CreatedBy = "created_by";
        public static String FieldName = "field_name";
        public static String DataType = "data_type";
        public static String BeforeValueString = "before_value_string";
        public static String AfterValueString = "after_value_string";
        public static String BeforeValueText = "before_value_text";
        public static String AfterValueText = "after_value_text";
    }

    public static class Calls {
        public static String SugarModuleName = "calls";
        public static String Id = "id";
        public static String Name = "name";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String DurationHours = "duration_hours";
        public static String DurationMinutes = "duration_minutes";
        public static String DateStart = "date_start";
        public static String DateEnd = "date_end";
        public static String ParentType = "parent_type";
        public static String Status = "status";
        public static String Direction = "direction";
        public static String ParentId = "parent_id";
        public static String ReminderTime = "reminder_time";
        public static String EmailReminderTime = "email_reminder_time";
        public static String EmailReminderSent = "email_reminder_sent";
        public static String OutlookId = "outlook_id";
        public static String RepeatType = "repeat_type";
        public static String RepeatInterval = "repeat_interval";
        public static String RepeatDow = "repeat_dow";
        public static String RepeatUntil = "repeat_until";
        public static String RepeatCount = "repeat_count";
        public static String RepeatParentId = "repeat_parent_id";
        public static String RecurringSource = "recurring_source";
    }

    public static class CallsContacts {
        public static String SugarModuleName = "calls_contacts";
        public static String Id = "id";
        public static String CallId = "call_id";
        public static String ContactId = "contact_id";
        public static String Required = "required";
        public static String AcceptStatus = "accept_status";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class CallsLeads {
        public static String SugarModuleName = "calls_leads";
        public static String Id = "id";
        public static String CallId = "call_id";
        public static String LeadId = "lead_id";
        public static String Required = "required";
        public static String AcceptStatus = "accept_status";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class CallsUsers {
        public static String SugarModuleName = "calls_users";
        public static String Id = "id";
        public static String CallId = "call_id";
        public static String UserId = "user_id";
        public static String Required = "required";
        public static String AcceptStatus = "accept_status";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class CampaignLog {
        public static String SugarModuleName = "campaign_log";
        public static String Id = "id";
        public static String CampaignId = "campaign_id";
        public static String TargetTrackerKey = "target_tracker_key";
        public static String TargetId = "target_id";
        public static String TargetType = "target_type";
        public static String ActivityType = "activity_type";
        public static String ActivityDate = "activity_date";
        public static String RelatedId = "related_id";
        public static String RelatedType = "related_type";
        public static String Archived = "archived";
        public static String Hits = "hits";
        public static String ListId = "list_id";
        public static String Deleted = "deleted";
        public static String DateModified = "date_modified";
        public static String MoreInformation = "more_information";
        public static String MarketingId = "marketing_id";
    }

    public static class CampaignTrkrs {
        public static String SugarModuleName = "campaign_trkrs";
        public static String Id = "id";
        public static String TrackerName = "tracker_name";
        public static String TrackerUrl = "tracker_url";
        public static String TrackerKey = "tracker_key";
        public static String CampaignId = "campaign_id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String IsOptout = "is_optout";
        public static String Deleted = "deleted";
    }

    public static class Campaigns {
        public static String SugarModuleName = "campaigns";
        public static String Id = "id";
        public static String Name = "name";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String TrackerKey = "tracker_key";
        public static String TrackerCount = "tracker_count";
        public static String ReferUrl = "refer_url";
        public static String TrackerText = "tracker_text";
        public static String StartDate = "start_date";
        public static String EndDate = "end_date";
        public static String Status = "status";
        public static String Impressions = "impressions";
        public static String CurrencyId = "currency_id";
        public static String Budget = "budget";
        public static String ExpectedCost = "expected_cost";
        public static String ActualCost = "actual_cost";
        public static String ExpectedRevenue = "expected_revenue";
        public static String CampaignType = "campaign_type";
        public static String Objective = "objective";
        public static String Content = "content";
        public static String Frequency = "frequency";
    }

    public static class CampaignsAudit {
        public static String SugarModuleName = "campaigns_audit";
        public static String Id = "id";
        public static String ParentId = "parent_id";
        public static String DateCreated = "date_created";
        public static String CreatedBy = "created_by";
        public static String FieldName = "field_name";
        public static String DataType = "data_type";
        public static String BeforeValueString = "before_value_string";
        public static String AfterValueString = "after_value_string";
        public static String BeforeValueText = "before_value_text";
        public static String AfterValueText = "after_value_text";
    }

    public static class Cases {
        public static String SugarModuleName = "cases";
        public static String Id = "id";
        public static String Name = "name";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String CaseNumber = "case_number";
        public static String Type = "type";
        public static String Status = "status";
        public static String Priority = "priority";
        public static String Resolution = "resolution";
        public static String WorkLog = "work_log";
        public static String AccountId = "account_id";
    }

    public static class CasesAudit {
        public static String SugarModuleName = "cases_audit";
        public static String Id = "id";
        public static String ParentId = "parent_id";
        public static String DateCreated = "date_created";
        public static String CreatedBy = "created_by";
        public static String FieldName = "field_name";
        public static String DataType = "data_type";
        public static String BeforeValueString = "before_value_string";
        public static String AfterValueString = "after_value_string";
        public static String BeforeValueText = "before_value_text";
        public static String AfterValueText = "after_value_text";
    }

    public static class CasesBugs {
        public static String SugarModuleName = "cases_bugs";
        public static String Id = "id";
        public static String CaseId = "case_id";
        public static String BugId = "bug_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class Config {
        public static String SugarModuleName = "config";
        public static String Category = "category";
        public static String Name = "name";
        public static String Value = "value";
    }

    public static class Contacts {
        public static String SugarModuleName = "contacts";
        public static String Id = "id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String Salutation = "salutation";
        public static String FirstName = "first_name";
        public static String LastName = "last_name";
        public static String Title = "title";
        public static String Department = "department";
        public static String DoNotCall = "do_not_call";
        public static String PhoneHome = "phone_home";
        public static String PhoneMobile = "phone_mobile";
        public static String PhoneWork = "phone_work";
        public static String PhoneOther = "phone_other";
        public static String PhoneFax = "phone_fax";
        public static String PrimaryAddressStreet = "primary_address_street";
        public static String PrimaryAddressCity = "primary_address_city";
        public static String PrimaryAddressState = "primary_address_state";
        public static String PrimaryAddressPostalcode = "primary_address_postalcode";
        public static String PrimaryAddressCountry = "primary_address_country";
        public static String AltAddressStreet = "alt_address_street";
        public static String AltAddressCity = "alt_address_city";
        public static String AltAddressState = "alt_address_state";
        public static String AltAddressPostalcode = "alt_address_postalcode";
        public static String AltAddressCountry = "alt_address_country";
        public static String Assistant = "assistant";
        public static String AssistantPhone = "assistant_phone";
        public static String LeadSource = "lead_source";
        public static String ReportsToId = "reports_to_id";
        public static String Birthdate = "birthdate";
        public static String CampaignId = "campaign_id";
    }

    public static class ContactsAudit {
        public static String SugarModuleName = "contacts_audit";
        public static String Id = "id";
        public static String ParentId = "parent_id";
        public static String DateCreated = "date_created";
        public static String CreatedBy = "created_by";
        public static String FieldName = "field_name";
        public static String DataType = "data_type";
        public static String BeforeValueString = "before_value_string";
        public static String AfterValueString = "after_value_string";
        public static String BeforeValueText = "before_value_text";
        public static String AfterValueText = "after_value_text";
    }

    public static class ContactsBugs {
        public static String SugarModuleName = "contacts_bugs";
        public static String Id = "id";
        public static String ContactId = "contact_id";
        public static String BugId = "bug_id";
        public static String ContactRole = "contact_role";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class ContactsCases {
        public static String SugarModuleName = "contacts_cases";
        public static String Id = "id";
        public static String ContactId = "contact_id";
        public static String CaseId = "case_id";
        public static String ContactRole = "contact_role";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class ContactsUsers {
        public static String SugarModuleName = "contacts_users";
        public static String Id = "id";
        public static String ContactId = "contact_id";
        public static String UserId = "user_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class CronRemoveDocuments {
        public static String SugarModuleName = "cron_remove_documents";
        public static String Id = "id";
        public static String BeanId = "bean_id";
        public static String Module = "module";
        public static String DateModified = "date_modified";
    }

    public static class Currencies {
        public static String SugarModuleName = "currencies";
        public static String Id = "id";
        public static String Name = "name";
        public static String Symbol = "symbol";
        public static String Iso4217 = "iso4217";
        public static String ConversionRate = "conversion_rate";
        public static String Status = "status";
        public static String Deleted = "deleted";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String CreatedBy = "created_by";
    }

    public static class CustomFields {
        public static String SugarModuleName = "custom_fields";
        public static String BeanId = "bean_id";
        public static String SetNum = "set_num";
        public static String Field0 = "field0";
        public static String Field1 = "field1";
        public static String Field2 = "field2";
        public static String Field3 = "field3";
        public static String Field4 = "field4";
        public static String Field5 = "field5";
        public static String Field6 = "field6";
        public static String Field7 = "field7";
        public static String Field8 = "field8";
        public static String Field9 = "field9";
        public static String Deleted = "deleted";
    }

    public static class DocumentRevisions {
        public static String SugarModuleName = "document_revisions";
        public static String Id = "id";
        public static String ChangeLog = "change_log";
        public static String DocumentId = "document_id";
        public static String DocId = "doc_id";
        public static String DocType = "doc_type";
        public static String DocUrl = "doc_url";
        public static String DateEntered = "date_entered";
        public static String CreatedBy = "created_by";
        public static String Filename = "filename";
        public static String FileExt = "file_ext";
        public static String FileMimeType = "file_mime_type";
        public static String Revision = "revision";
        public static String Deleted = "deleted";
        public static String DateModified = "date_modified";
    }

    public static class Documents {
        public static String SugarModuleName = "documents";
        public static String Id = "id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String DocumentName = "document_name";
        public static String DocId = "doc_id";
        public static String DocType = "doc_type";
        public static String DocUrl = "doc_url";
        public static String ActiveDate = "active_date";
        public static String ExpDate = "exp_date";
        public static String CategoryId = "category_id";
        public static String SubcategoryId = "subcategory_id";
        public static String StatusId = "status_id";
        public static String DocumentRevisionId = "document_revision_id";
        public static String RelatedDocId = "related_doc_id";
        public static String RelatedDocRevId = "related_doc_rev_id";
        public static String IsTemplate = "is_template";
        public static String TemplateType = "template_type";
    }

    public static class DocumentsAccounts {
        public static String SugarModuleName = "documents_accounts";
        public static String Id = "id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
        public static String DocumentId = "document_id";
        public static String AccountId = "account_id";
    }

    public static class DocumentsBugs {
        public static String SugarModuleName = "documents_bugs";
        public static String Id = "id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
        public static String DocumentId = "document_id";
        public static String BugId = "bug_id";
    }

    public static class DocumentsCases {
        public static String SugarModuleName = "documents_cases";
        public static String Id = "id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
        public static String DocumentId = "document_id";
        public static String CaseId = "case_id";
    }

    public static class DocumentsContacts {
        public static String SugarModuleName = "documents_contacts";
        public static String Id = "id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
        public static String DocumentId = "document_id";
        public static String ContactId = "contact_id";
    }

    public static class DocumentsOpportunities {
        public static String SugarModuleName = "documents_opportunities";
        public static String Id = "id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
        public static String DocumentId = "document_id";
        public static String OpportunityId = "opportunity_id";
    }

    public static class Eapm {
        public static String SugarModuleName = "eapm";
        public static String Id = "id";
        public static String Name = "name";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String Password = "password";
        public static String Url = "url";
        public static String Application = "application";
        public static String ApiData = "api_data";
        public static String ConsumerKey = "consumer_key";
        public static String ConsumerSecret = "consumer_secret";
        public static String OauthToken = "oauth_token";
        public static String OauthSecret = "oauth_secret";
        public static String Validated = "validated";
    }

    public static class EmailAddrBeanRel {
        public static String SugarModuleName = "email_addr_bean_rel";
        public static String Id = "id";
        public static String EmailAddressId = "email_address_id";
        public static String BeanId = "bean_id";
        public static String BeanModule = "bean_module";
        public static String PrimaryAddress = "primary_address";
        public static String ReplyToAddress = "reply_to_address";
        public static String DateCreated = "date_created";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class EmailAddresses {
        public static String SugarModuleName = "email_addresses";
        public static String Id = "id";
        public static String EmailAddress = "email_address";
        public static String EmailAddressCaps = "email_address_caps";
        public static String InvalidEmail = "invalid_email";
        public static String OptOut = "opt_out";
        public static String DateCreated = "date_created";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class EmailCache {
        public static String SugarModuleName = "email_cache";
        public static String IeId = "ie_id";
        public static String Mbox = "mbox";
        public static String Subject = "subject";
        public static String Fromaddr = "fromaddr";
        public static String Toaddr = "toaddr";
        public static String Senddate = "senddate";
        public static String MessageId = "message_id";
        public static String Mailsize = "mailsize";
        public static String ImapUid = "imap_uid";
        public static String Msgno = "msgno";
        public static String Recent = "recent";
        public static String Flagged = "flagged";
        public static String Answered = "answered";
        public static String Deleted = "deleted";
        public static String Seen = "seen";
        public static String Draft = "draft";
    }

    public static class EmailMarketing {
        public static String SugarModuleName = "email_marketing";
        public static String Id = "id";
        public static String Deleted = "deleted";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Name = "name";
        public static String FromName = "from_name";
        public static String FromAddr = "from_addr";
        public static String ReplyToName = "reply_to_name";
        public static String ReplyToAddr = "reply_to_addr";
        public static String InboundEmailId = "inbound_email_id";
        public static String DateStart = "date_start";
        public static String TemplateId = "template_id";
        public static String Status = "status";
        public static String CampaignId = "campaign_id";
        public static String AllProspectLists = "all_prospect_lists";
    }

    public static class EmailMarketingProspectLists {
        public static String SugarModuleName = "email_marketing_prospect_lists";
        public static String Id = "id";
        public static String ProspectListId = "prospect_list_id";
        public static String EmailMarketingId = "email_marketing_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class EmailTemplates {
        public static String SugarModuleName = "email_templates";
        public static String Id = "id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Published = "published";
        public static String Name = "name";
        public static String Description = "description";
        public static String Subject = "subject";
        public static String Body = "body";
        public static String BodyHtml = "body_html";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String TextOnly = "text_only";
        public static String Type = "type";
    }

    public static class Emailman {
        public static String SugarModuleName = "emailman";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String UserId = "user_id";
        public static String Id = "id";
        public static String CampaignId = "campaign_id";
        public static String MarketingId = "marketing_id";
        public static String ListId = "list_id";
        public static String SendDateTime = "send_date_time";
        public static String ModifiedUserId = "modified_user_id";
        public static String InQueue = "in_queue";
        public static String InQueueDate = "in_queue_date";
        public static String SendAttempts = "send_attempts";
        public static String Deleted = "deleted";
        public static String RelatedId = "related_id";
        public static String RelatedType = "related_type";
    }

    public static class Emails {
        public static String SugarModuleName = "emails";
        public static String Id = "id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String AssignedUserId = "assigned_user_id";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Deleted = "deleted";
        public static String DateSent = "date_sent";
        public static String MessageId = "message_id";
        public static String Name = "name";
        public static String Type = "type";
        public static String Status = "status";
        public static String Flagged = "flagged";
        public static String ReplyToStatus = "reply_to_status";
        public static String Intent = "intent";
        public static String MailboxId = "mailbox_id";
        public static String ParentType = "parent_type";
        public static String ParentId = "parent_id";
    }

    public static class EmailsBeans {
        public static String SugarModuleName = "emails_beans";
        public static String Id = "id";
        public static String EmailId = "email_id";
        public static String BeanId = "bean_id";
        public static String BeanModule = "bean_module";
        public static String CampaignData = "campaign_data";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class EmailsEmailAddrRel {
        public static String SugarModuleName = "emails_email_addr_rel";
        public static String Id = "id";
        public static String EmailId = "email_id";
        public static String AddressType = "address_type";
        public static String EmailAddressId = "email_address_id";
        public static String Deleted = "deleted";
    }

    public static class EmailsText {
        public static String SugarModuleName = "emails_text";
        public static String EmailId = "email_id";
        public static String FromAddr = "from_addr";
        public static String ReplyToAddr = "reply_to_addr";
        public static String ToAddrs = "to_addrs";
        public static String CcAddrs = "cc_addrs";
        public static String BccAddrs = "bcc_addrs";
        public static String Description = "description";
        public static String DescriptionHtml = "description_html";
        public static String RawSource = "raw_source";
        public static String Deleted = "deleted";
    }

    public static class FieldsMetaData {
        public static String SugarModuleName = "fields_meta_data";
        public static String Id = "id";
        public static String Name = "name";
        public static String Vname = "vname";
        public static String Comments = "comments";
        public static String Help = "help";
        public static String CustomModule = "custom_module";
        public static String Type = "type";
        public static String Len = "len";
        public static String Required = "required";
        public static String DefaultValue = "default_value";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
        public static String Audited = "audited";
        public static String Massupdate = "massupdate";
        public static String DuplicateMerge = "duplicate_merge";
        public static String Reportable = "reportable";
        public static String Importable = "importable";
        public static String Ext1 = "ext1";
        public static String Ext2 = "ext2";
        public static String Ext3 = "ext3";
        public static String Ext4 = "ext4";
    }

    public static class Folders {
        public static String SugarModuleName = "folders";
        public static String Id = "id";
        public static String Name = "name";
        public static String FolderType = "folder_type";
        public static String ParentFolder = "parent_folder";
        public static String HasChild = "has_child";
        public static String IsGroup = "is_group";
        public static String IsDynamic = "is_dynamic";
        public static String DynamicQuery = "dynamic_query";
        public static String AssignToId = "assign_to_id";
        public static String CreatedBy = "created_by";
        public static String ModifiedBy = "modified_by";
        public static String Deleted = "deleted";
    }

    public static class FoldersRel {
        public static String SugarModuleName = "folders_rel";
        public static String Id = "id";
        public static String FolderId = "folder_id";
        public static String PolymorphicModule = "polymorphic_module";
        public static String PolymorphicId = "polymorphic_id";
        public static String Deleted = "deleted";
    }

    public static class FoldersSubscriptions {
        public static String SugarModuleName = "folders_subscriptions";
        public static String Id = "id";
        public static String FolderId = "folder_id";
        public static String AssignedUserId = "assigned_user_id";
    }

    public static class ImportMaps {
        public static String SugarModuleName = "import_maps";
        public static String Id = "id";
        public static String Name = "name";
        public static String Source = "source";
        public static String Enclosure = "enclosure";
        public static String Delimiter = "delimiter";
        public static String Module = "module";
        public static String Content = "content";
        public static String DefaultValues = "default_values";
        public static String HasHeader = "has_header";
        public static String Deleted = "deleted";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String AssignedUserId = "assigned_user_id";
        public static String IsPublished = "is_published";
    }

    public static class InboundEmail {
        public static String SugarModuleName = "inbound_email";
        public static String Id = "id";
        public static String Deleted = "deleted";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Name = "name";
        public static String Status = "status";
        public static String ServerUrl = "server_url";
        public static String EmailUser = "email_user";
        public static String EmailPassword = "email_password";
        public static String Port = "port";
        public static String Service = "service";
        public static String Mailbox = "mailbox";
        public static String DeleteSeen = "delete_seen";
        public static String MailboxType = "mailbox_type";
        public static String TemplateId = "template_id";
        public static String StoredOptions = "stored_options";
        public static String GroupId = "group_id";
        public static String IsPersonal = "is_personal";
        public static String GroupfolderId = "groupfolder_id";
    }

    public static class InboundEmailAutoreply {
        public static String SugarModuleName = "inbound_email_autoreply";
        public static String Id = "id";
        public static String Deleted = "deleted";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String AutorepliedTo = "autoreplied_to";
        public static String IeId = "ie_id";
    }

    public static class InboundEmailCacheTs {
        public static String SugarModuleName = "inbound_email_cache_ts";
        public static String Id = "id";
        public static String IeTimestamp = "ie_timestamp";
    }

    public static class JobQueue {
        public static String SugarModuleName = "job_queue";
        public static String AssignedUserId = "assigned_user_id";
        public static String Id = "id";
        public static String Name = "name";
        public static String Deleted = "deleted";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String SchedulerId = "scheduler_id";
        public static String ExecuteTime = "execute_time";
        public static String Status = "status";
        public static String Resolution = "resolution";
        public static String Message = "message";
        public static String Target = "target";
        public static String Data = "data";
        public static String Requeue = "requeue";
        public static String RetryCount = "retry_count";
        public static String FailureCount = "failure_count";
        public static String JobDelay = "job_delay";
        public static String Client = "client";
        public static String PercentComplete = "percent_complete";
    }

    public static class Leads {
        public static String SugarModuleName = "leads";
        public static String Id = "id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String Salutation = "salutation";
        public static String FirstName = "first_name";
        public static String LastName = "last_name";
        public static String Title = "title";
        public static String Department = "department";
        public static String DoNotCall = "do_not_call";
        public static String PhoneHome = "phone_home";
        public static String PhoneMobile = "phone_mobile";
        public static String PhoneWork = "phone_work";
        public static String PhoneOther = "phone_other";
        public static String PhoneFax = "phone_fax";
        public static String PrimaryAddressStreet = "primary_address_street";
        public static String PrimaryAddressCity = "primary_address_city";
        public static String PrimaryAddressState = "primary_address_state";
        public static String PrimaryAddressPostalcode = "primary_address_postalcode";
        public static String PrimaryAddressCountry = "primary_address_country";
        public static String AltAddressStreet = "alt_address_street";
        public static String AltAddressCity = "alt_address_city";
        public static String AltAddressState = "alt_address_state";
        public static String AltAddressPostalcode = "alt_address_postalcode";
        public static String AltAddressCountry = "alt_address_country";
        public static String Assistant = "assistant";
        public static String AssistantPhone = "assistant_phone";
        public static String Converted = "converted";
        public static String ReferedBy = "refered_by";
        public static String LeadSource = "lead_source";
        public static String LeadSourceDescription = "lead_source_description";
        public static String Status = "status";
        public static String StatusDescription = "status_description";
        public static String ReportsToId = "reports_to_id";
        public static String AccountName = "account_name";
        public static String AccountDescription = "account_description";
        public static String ContactId = "contact_id";
        public static String AccountId = "account_id";
        public static String OpportunityId = "opportunity_id";
        public static String OpportunityName = "opportunity_name";
        public static String OpportunityAmount = "opportunity_amount";
        public static String CampaignId = "campaign_id";
        public static String Birthdate = "birthdate";
        public static String PortalName = "portal_name";
        public static String PortalApp = "portal_app";
        public static String Website = "website";
    }

    public static class LeadsAudit {
        public static String SugarModuleName = "leads_audit";
        public static String Id = "id";
        public static String ParentId = "parent_id";
        public static String DateCreated = "date_created";
        public static String CreatedBy = "created_by";
        public static String FieldName = "field_name";
        public static String DataType = "data_type";
        public static String BeforeValueString = "before_value_string";
        public static String AfterValueString = "after_value_string";
        public static String BeforeValueText = "before_value_text";
        public static String AfterValueText = "after_value_text";
    }

    public static class LinkedDocuments {
        public static String SugarModuleName = "linked_documents";
        public static String Id = "id";
        public static String ParentId = "parent_id";
        public static String ParentType = "parent_type";
        public static String DocumentId = "document_id";
        public static String DocumentRevisionId = "document_revision_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class Meetings {
        public static String SugarModuleName = "meetings";
        public static String Id = "id";
        public static String Name = "name";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String Location = "location";
        public static String Password = "password";
        public static String JoinUrl = "join_url";
        public static String HostUrl = "host_url";
        public static String DisplayedUrl = "displayed_url";
        public static String Creator = "creator";
        public static String ExternalId = "external_id";
        public static String DurationHours = "duration_hours";
        public static String DurationMinutes = "duration_minutes";
        public static String DateStart = "date_start";
        public static String DateEnd = "date_end";
        public static String ParentType = "parent_type";
        public static String Status = "status";
        public static String Type = "type";
        public static String ParentId = "parent_id";
        public static String ReminderTime = "reminder_time";
        public static String EmailReminderTime = "email_reminder_time";
        public static String EmailReminderSent = "email_reminder_sent";
        public static String OutlookId = "outlook_id";
        public static String Sequence = "sequence";
        public static String RepeatType = "repeat_type";
        public static String RepeatInterval = "repeat_interval";
        public static String RepeatDow = "repeat_dow";
        public static String RepeatUntil = "repeat_until";
        public static String RepeatCount = "repeat_count";
        public static String RepeatParentId = "repeat_parent_id";
        public static String RecurringSource = "recurring_source";
    }

    public static class MeetingsContacts {
        public static String SugarModuleName = "meetings_contacts";
        public static String Id = "id";
        public static String MeetingId = "meeting_id";
        public static String ContactId = "contact_id";
        public static String Required = "required";
        public static String AcceptStatus = "accept_status";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class MeetingsLeads {
        public static String SugarModuleName = "meetings_leads";
        public static String Id = "id";
        public static String MeetingId = "meeting_id";
        public static String LeadId = "lead_id";
        public static String Required = "required";
        public static String AcceptStatus = "accept_status";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class MeetingsUsers {
        public static String SugarModuleName = "meetings_users";
        public static String Id = "id";
        public static String MeetingId = "meeting_id";
        public static String UserId = "user_id";
        public static String Required = "required";
        public static String AcceptStatus = "accept_status";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class Notes {
        public static String SugarModuleName = "notes";
        public static String AssignedUserId = "assigned_user_id";
        public static String Id = "id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Name = "name";
        public static String FileMimeType = "file_mime_type";
        public static String Filename = "filename";
        public static String ParentType = "parent_type";
        public static String ParentId = "parent_id";
        public static String ContactId = "contact_id";
        public static String PortalFlag = "portal_flag";
        public static String EmbedFlag = "embed_flag";
        public static String Description = "description";
        public static String Deleted = "deleted";
    }

    public static class OauthConsumer {
        public static String SugarModuleName = "oauth_consumer";
        public static String Id = "id";
        public static String Name = "name";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String CKey = "c_key";
        public static String CSecret = "c_secret";
    }

    public static class OauthNonce {
        public static String SugarModuleName = "oauth_nonce";
        public static String Conskey = "conskey";
        public static String Nonce = "nonce";
        public static String NonceTs = "nonce_ts";
    }

    public static class OauthTokens {
        public static String SugarModuleName = "oauth_tokens";
        public static String Id = "id";
        public static String Secret = "secret";
        public static String Tstate = "tstate";
        public static String Consumer = "consumer";
        public static String TokenTs = "token_ts";
        public static String Verify = "verify";
        public static String Deleted = "deleted";
        public static String CallbackUrl = "callback_url";
        public static String AssignedUserId = "assigned_user_id";
    }

    public static class Opportunities {
        public static String SugarModuleName = "opportunities";
        public static String Id = "id";
        public static String Name = "name";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String OpportunityType = "opportunity_type";
        public static String CampaignId = "campaign_id";
        public static String LeadSource = "lead_source";
        public static String Amount = "amount";
        public static String AmountUsdollar = "amount_usdollar";
        public static String CurrencyId = "currency_id";
        public static String DateClosed = "date_closed";
        public static String NextStep = "next_step";
        public static String SalesStage = "sales_stage";
        public static String Probability = "probability";
    }

    public static class OpportunitiesAudit {
        public static String SugarModuleName = "opportunities_audit";
        public static String Id = "id";
        public static String ParentId = "parent_id";
        public static String DateCreated = "date_created";
        public static String CreatedBy = "created_by";
        public static String FieldName = "field_name";
        public static String DataType = "data_type";
        public static String BeforeValueString = "before_value_string";
        public static String AfterValueString = "after_value_string";
        public static String BeforeValueText = "before_value_text";
        public static String AfterValueText = "after_value_text";
    }

    public static class OpportunitiesContacts {
        public static String SugarModuleName = "opportunities_contacts";
        public static String Id = "id";
        public static String ContactId = "contact_id";
        public static String OpportunityId = "opportunity_id";
        public static String ContactRole = "contact_role";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class OutboundEmail {
        public static String SugarModuleName = "outbound_email";
        public static String Id = "id";
        public static String Name = "name";
        public static String Type = "type";
        public static String UserId = "user_id";
        public static String MailSendtype = "mail_sendtype";
        public static String MailSmtptype = "mail_smtptype";
        public static String MailSmtpserver = "mail_smtpserver";
        public static String MailSmtpport = "mail_smtpport";
        public static String MailSmtpuser = "mail_smtpuser";
        public static String MailSmtppass = "mail_smtppass";
        public static String MailSmtpauthReq = "mail_smtpauth_req";
        public static String MailSmtpssl = "mail_smtpssl";
    }

    public static class Project {
        public static String SugarModuleName = "project";
        public static String Id = "id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String AssignedUserId = "assigned_user_id";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Name = "name";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String EstimatedStartDate = "estimated_start_date";
        public static String EstimatedEndDate = "estimated_end_date";
        public static String Status = "status";
        public static String Priority = "priority";
    }

    public static class ProjectTask {
        public static String SugarModuleName = "project_task";
        public static String Id = "id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ProjectId = "project_id";
        public static String ProjectTaskId = "project_task_id";
        public static String Name = "name";
        public static String Status = "status";
        public static String Description = "description";
        public static String Predecessors = "predecessors";
        public static String DateStart = "date_start";
        public static String TimeStart = "time_start";
        public static String TimeFinish = "time_finish";
        public static String DateFinish = "date_finish";
        public static String Duration = "duration";
        public static String DurationUnit = "duration_unit";
        public static String ActualDuration = "actual_duration";
        public static String PercentComplete = "percent_complete";
        public static String DateDue = "date_due";
        public static String TimeDue = "time_due";
        public static String ParentTaskId = "parent_task_id";
        public static String AssignedUserId = "assigned_user_id";
        public static String ModifiedUserId = "modified_user_id";
        public static String Priority = "priority";
        public static String CreatedBy = "created_by";
        public static String MilestoneFlag = "milestone_flag";
        public static String OrderNumber = "order_number";
        public static String TaskNumber = "task_number";
        public static String EstimatedEffort = "estimated_effort";
        public static String ActualEffort = "actual_effort";
        public static String Deleted = "deleted";
        public static String Utilization = "utilization";
    }

    public static class ProjectTaskAudit {
        public static String SugarModuleName = "project_task_audit";
        public static String Id = "id";
        public static String ParentId = "parent_id";
        public static String DateCreated = "date_created";
        public static String CreatedBy = "created_by";
        public static String FieldName = "field_name";
        public static String DataType = "data_type";
        public static String BeforeValueString = "before_value_string";
        public static String AfterValueString = "after_value_string";
        public static String BeforeValueText = "before_value_text";
        public static String AfterValueText = "after_value_text";
    }

    public static class ProjectsAccounts {
        public static String SugarModuleName = "projects_accounts";
        public static String Id = "id";
        public static String AccountId = "account_id";
        public static String ProjectId = "project_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class ProjectsBugs {
        public static String SugarModuleName = "projects_bugs";
        public static String Id = "id";
        public static String BugId = "bug_id";
        public static String ProjectId = "project_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class ProjectsCases {
        public static String SugarModuleName = "projects_cases";
        public static String Id = "id";
        public static String CaseId = "case_id";
        public static String ProjectId = "project_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class ProjectsContacts {
        public static String SugarModuleName = "projects_contacts";
        public static String Id = "id";
        public static String ContactId = "contact_id";
        public static String ProjectId = "project_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class ProjectsOpportunities {
        public static String SugarModuleName = "projects_opportunities";
        public static String Id = "id";
        public static String OpportunityId = "opportunity_id";
        public static String ProjectId = "project_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class ProjectsProducts {
        public static String SugarModuleName = "projects_products";
        public static String Id = "id";
        public static String ProductId = "product_id";
        public static String ProjectId = "project_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class ProspectListCampaigns {
        public static String SugarModuleName = "prospect_list_campaigns";
        public static String Id = "id";
        public static String ProspectListId = "prospect_list_id";
        public static String CampaignId = "campaign_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class ProspectLists {
        public static String SugarModuleName = "prospect_lists";
        public static String AssignedUserId = "assigned_user_id";
        public static String Id = "id";
        public static String Name = "name";
        public static String ListType = "list_type";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Deleted = "deleted";
        public static String Description = "description";
        public static String DomainName = "domain_name";
    }

    public static class ProspectListsProspects {
        public static String SugarModuleName = "prospect_lists_prospects";
        public static String Id = "id";
        public static String ProspectListId = "prospect_list_id";
        public static String RelatedId = "related_id";
        public static String RelatedType = "related_type";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class Prospects {
        public static String SugarModuleName = "prospects";
        public static String Id = "id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String Salutation = "salutation";
        public static String FirstName = "first_name";
        public static String LastName = "last_name";
        public static String Title = "title";
        public static String Department = "department";
        public static String DoNotCall = "do_not_call";
        public static String PhoneHome = "phone_home";
        public static String PhoneMobile = "phone_mobile";
        public static String PhoneWork = "phone_work";
        public static String PhoneOther = "phone_other";
        public static String PhoneFax = "phone_fax";
        public static String PrimaryAddressStreet = "primary_address_street";
        public static String PrimaryAddressCity = "primary_address_city";
        public static String PrimaryAddressState = "primary_address_state";
        public static String PrimaryAddressPostalcode = "primary_address_postalcode";
        public static String PrimaryAddressCountry = "primary_address_country";
        public static String AltAddressStreet = "alt_address_street";
        public static String AltAddressCity = "alt_address_city";
        public static String AltAddressState = "alt_address_state";
        public static String AltAddressPostalcode = "alt_address_postalcode";
        public static String AltAddressCountry = "alt_address_country";
        public static String Assistant = "assistant";
        public static String AssistantPhone = "assistant_phone";
        public static String TrackerKey = "tracker_key";
        public static String Birthdate = "birthdate";
        public static String LeadId = "lead_id";
        public static String AccountName = "account_name";
        public static String CampaignId = "campaign_id";
    }

    public static class Relationships {
        public static String SugarModuleName = "relationships";
        public static String Id = "id";
        public static String RelationshipName = "relationship_name";
        public static String LhsModule = "lhs_module";
        public static String LhsTable = "lhs_table";
        public static String LhsKey = "lhs_key";
        public static String RhsModule = "rhs_module";
        public static String RhsTable = "rhs_table";
        public static String RhsKey = "rhs_key";
        public static String JoinTable = "join_table";
        public static String JoinKeyLhs = "join_key_lhs";
        public static String JoinKeyRhs = "join_key_rhs";
        public static String RelationshipType = "relationship_type";
        public static String RelationshipRoleColumn = "relationship_role_column";
        public static String RelationshipRoleColumnValue = "relationship_role_column_value";
        public static String Reverse = "reverse";
        public static String Deleted = "deleted";
    }

    public static class Releases {
        public static String SugarModuleName = "releases";
        public static String Id = "id";
        public static String Deleted = "deleted";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Name = "name";
        public static String ListOrder = "list_order";
        public static String Status = "status";
    }

    public static class Roles {
        public static String SugarModuleName = "roles";
        public static String Id = "id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Name = "name";
        public static String Description = "description";
        public static String Modules = "modules";
        public static String Deleted = "deleted";
    }

    public static class RolesModules {
        public static String SugarModuleName = "roles_modules";
        public static String Id = "id";
        public static String RoleId = "role_id";
        public static String ModuleId = "module_id";
        public static String Allow = "allow";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class RolesUsers {
        public static String SugarModuleName = "roles_users";
        public static String Id = "id";
        public static String RoleId = "role_id";
        public static String UserId = "user_id";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class SavedSearch {
        public static String SugarModuleName = "saved_search";
        public static String Id = "id";
        public static String Name = "name";
        public static String SearchModule = "search_module";
        public static String Deleted = "deleted";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String AssignedUserId = "assigned_user_id";
        public static String Contents = "contents";
        public static String Description = "description";
    }

    public static class Schedulers {
        public static String SugarModuleName = "schedulers";
        public static String Id = "id";
        public static String Deleted = "deleted";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String CreatedBy = "created_by";
        public static String ModifiedUserId = "modified_user_id";
        public static String Name = "name";
        public static String Job = "job";
        public static String DateTimeStart = "date_time_start";
        public static String DateTimeEnd = "date_time_end";
        public static String JobInterval = "job_interval";
        public static String TimeFrom = "time_from";
        public static String TimeTo = "time_to";
        public static String LastRun = "last_run";
        public static String Status = "status";
        public static String CatchUp = "catch_up";
    }

    public static class Sugarfeed {
        public static String SugarModuleName = "sugarfeed";
        public static String Id = "id";
        public static String Name = "name";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String RelatedModule = "related_module";
        public static String RelatedId = "related_id";
        public static String LinkUrl = "link_url";
        public static String LinkType = "link_type";
    }

    public static class Tasks {
        public static String SugarModuleName = "tasks";
        public static String Id = "id";
        public static String Name = "name";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Description = "description";
        public static String Deleted = "deleted";
        public static String AssignedUserId = "assigned_user_id";
        public static String Status = "status";
        public static String DateDueFlag = "date_due_flag";
        public static String DateDue = "date_due";
        public static String DateStartFlag = "date_start_flag";
        public static String DateStart = "date_start";
        public static String ParentType = "parent_type";
        public static String ParentId = "parent_id";
        public static String ContactId = "contact_id";
        public static String Priority = "priority";
    }

    public static class Tracker {
        public static String SugarModuleName = "tracker";
        public static String Id = "id";
        public static String MonitorId = "monitor_id";
        public static String UserId = "user_id";
        public static String ModuleName = "module_name";
        public static String ItemId = "item_id";
        public static String ItemSummary = "item_summary";
        public static String DateModified = "date_modified";
        public static String Action = "action";
        public static String SessionId = "session_id";
        public static String Visible = "visible";
        public static String Deleted = "deleted";
    }

    public static class UpgradeHistory {
        public static String SugarModuleName = "upgrade_history";
        public static String Id = "id";
        public static String Filename = "filename";
        public static String Md5sum = "md5sum";
        public static String Type = "type";
        public static String Status = "status";
        public static String Version = "version";
        public static String Name = "name";
        public static String Description = "description";
        public static String IdName = "id_name";
        public static String Manifest = "manifest";
        public static String DateEntered = "date_entered";
        public static String Enabled = "enabled";
    }

    public static class UserPreferences {
        public static String SugarModuleName = "user_preferences";
        public static String Id = "id";
        public static String Category = "category";
        public static String Deleted = "deleted";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String AssignedUserId = "assigned_user_id";
        public static String Contents = "contents";
    }

    public static class Users {
        public static String SugarModuleName = "users";
        public static String Id = "id";
        public static String UserName = "user_name";
        public static String UserHash = "user_hash";
        public static String SystemGeneratedPassword = "system_generated_password";
        public static String PwdLastChanged = "pwd_last_changed";
        public static String AuthenticateId = "authenticate_id";
        public static String SugarLogin = "sugar_login";
        public static String FirstName = "first_name";
        public static String LastName = "last_name";
        public static String IsAdmin = "is_admin";
        public static String ExternalAuthOnly = "external_auth_only";
        public static String ReceiveNotifications = "receive_notifications";
        public static String Description = "description";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Title = "title";
        public static String Department = "department";
        public static String PhoneHome = "phone_home";
        public static String PhoneMobile = "phone_mobile";
        public static String PhoneWork = "phone_work";
        public static String PhoneOther = "phone_other";
        public static String PhoneFax = "phone_fax";
        public static String Status = "status";
        public static String AddressStreet = "address_street";
        public static String AddressCity = "address_city";
        public static String AddressState = "address_state";
        public static String AddressCountry = "address_country";
        public static String AddressPostalcode = "address_postalcode";
        public static String Deleted = "deleted";
        public static String PortalOnly = "portal_only";
        public static String ShowOnEmployees = "show_on_employees";
        public static String EmployeeStatus = "employee_status";
        public static String MessengerId = "messenger_id";
        public static String MessengerType = "messenger_type";
        public static String ReportsToId = "reports_to_id";
        public static String IsGroup = "is_group";
    }

    public static class UsersFeeds {
        public static String SugarModuleName = "users_feeds";
        public static String UserId = "user_id";
        public static String FeedId = "feed_id";
        public static String Rank = "rank";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
    }

    public static class UsersLastImport {
        public static String SugarModuleName = "users_last_import";
        public static String Id = "id";
        public static String AssignedUserId = "assigned_user_id";
        public static String ImportModule = "import_module";
        public static String BeanType = "bean_type";
        public static String BeanId = "bean_id";
        public static String Deleted = "deleted";
    }

    public static class UsersPasswordLink {
        public static String SugarModuleName = "users_password_link";
        public static String Id = "id";
        public static String Username = "username";
        public static String DateGenerated = "date_generated";
        public static String Deleted = "deleted";
    }

    public static class UsersSignatures {
        public static String SugarModuleName = "users_signatures";
        public static String Id = "id";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String Deleted = "deleted";
        public static String UserId = "user_id";
        public static String Name = "name";
        public static String Signature = "signature";
        public static String SignatureHtml = "signature_html";
    }

    public static class Vcals {
        public static String SugarModuleName = "vcals";
        public static String Id = "id";
        public static String Deleted = "deleted";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String UserId = "user_id";
        public static String Type = "type";
        public static String Source = "source";
        public static String Content = "content";
    }

    public static class Versions {
        public static String SugarModuleName = "versions";
        public static String Id = "id";
        public static String Deleted = "deleted";
        public static String DateEntered = "date_entered";
        public static String DateModified = "date_modified";
        public static String ModifiedUserId = "modified_user_id";
        public static String CreatedBy = "created_by";
        public static String Name = "name";
        public static String FileVersion = "file_version";
        public static String DbVersion = "db_version";
    }

}