/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the acl_roles_actions table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "", tablename = "acl_roles_actions")
@JsonRootName(value = "acl_roles_actions")
@JsonIgnoreProperties(ignoreUnknown = true)
public class AclRolesActions {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getRoleId() {
        return roleId;
    }

    public void setRoleId(String value) {
        roleId = value;
    }
    public String getActionId() {
        return actionId;
    }

    public void setActionId(String value) {
        actionId = value;
    }
    public Integer getAccessOverride() {
        return accessOverride;
    }

    public void setAccessOverride(Integer value) {
        accessOverride = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("role_id")
    private String roleId;
  
    @JsonProperty("action_id")
    private String actionId;
  
    @JsonProperty("access_override")
    private Integer accessOverride;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
}
