/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the campaign_log table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "CampaignLog", tablename = "campaign_log")
@JsonRootName(value = "campaign_log")
@JsonIgnoreProperties(ignoreUnknown = true)
public class CampaignLog {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getCampaignId() {
        return campaignId;
    }

    public void setCampaignId(String value) {
        campaignId = value;
    }
    public String getTargetTrackerKey() {
        return targetTrackerKey;
    }

    public void setTargetTrackerKey(String value) {
        targetTrackerKey = value;
    }
    public String getTargetId() {
        return targetId;
    }

    public void setTargetId(String value) {
        targetId = value;
    }
    public String getTargetType() {
        return targetType;
    }

    public void setTargetType(String value) {
        targetType = value;
    }
    public String getActivityType() {
        return activityType;
    }

    public void setActivityType(String value) {
        activityType = value;
    }
    public Date getActivityDate() {
        return activityDate;
    }

    public void setActivityDate(Date value) {
        activityDate = value;
    }
    public String getRelatedId() {
        return relatedId;
    }

    public void setRelatedId(String value) {
        relatedId = value;
    }
    public String getRelatedType() {
        return relatedType;
    }

    public void setRelatedType(String value) {
        relatedType = value;
    }
    public Integer getArchived() {
        return archived;
    }

    public void setArchived(Integer value) {
        archived = value;
    }
    public Integer getHits() {
        return hits;
    }

    public void setHits(Integer value) {
        hits = value;
    }
    public String getListId() {
        return listId;
    }

    public void setListId(String value) {
        listId = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public String getMoreInformation() {
        return moreInformation;
    }

    public void setMoreInformation(String value) {
        moreInformation = value;
    }
    public String getMarketingId() {
        return marketingId;
    }

    public void setMarketingId(String value) {
        marketingId = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("campaign_id")
    private String campaignId;
  
    @JsonProperty("target_tracker_key")
    private String targetTrackerKey;
  
    @JsonProperty("target_id")
    private String targetId;
  
    @JsonProperty("target_type")
    private String targetType;
  
    @JsonProperty("activity_type")
    private String activityType;
  
    @JsonProperty("activity_date")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date activityDate;
  
    @JsonProperty("related_id")
    private String relatedId;
  
    @JsonProperty("related_type")
    private String relatedType;
  
    @JsonProperty("archived")
    private Integer archived;
  
    @JsonProperty("hits")
    private Integer hits;
  
    @JsonProperty("list_id")
    private String listId;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("more_information")
    private String moreInformation;
  
    @JsonProperty("marketing_id")
    private String marketingId;
  
}
