/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the cron_remove_documents table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "", tablename = "cron_remove_documents")
@JsonRootName(value = "cron_remove_documents")
@JsonIgnoreProperties(ignoreUnknown = true)
public class CronRemoveDocuments {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getBeanId() {
        return beanId;
    }

    public void setBeanId(String value) {
        beanId = value;
    }
    public String getModule() {
        return module;
    }

    public void setModule(String value) {
        module = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("bean_id")
    private String beanId;
  
    @JsonProperty("module")
    private String module;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
}
