/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the custom_fields table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;


@Module(name = "", tablename = "custom_fields")
@JsonRootName(value = "custom_fields")
@JsonIgnoreProperties(ignoreUnknown = true)
public class CustomFields {
    public String getBeanId() {
        return beanId;
    }

    public void setBeanId(String value) {
        beanId = value;
    }
    public Integer getSetNum() {
        return setNum;
    }

    public void setSetNum(Integer value) {
        setNum = value;
    }
    public String getField0() {
        return field0;
    }

    public void setField0(String value) {
        field0 = value;
    }
    public String getField1() {
        return field1;
    }

    public void setField1(String value) {
        field1 = value;
    }
    public String getField2() {
        return field2;
    }

    public void setField2(String value) {
        field2 = value;
    }
    public String getField3() {
        return field3;
    }

    public void setField3(String value) {
        field3 = value;
    }
    public String getField4() {
        return field4;
    }

    public void setField4(String value) {
        field4 = value;
    }
    public String getField5() {
        return field5;
    }

    public void setField5(String value) {
        field5 = value;
    }
    public String getField6() {
        return field6;
    }

    public void setField6(String value) {
        field6 = value;
    }
    public String getField7() {
        return field7;
    }

    public void setField7(String value) {
        field7 = value;
    }
    public String getField8() {
        return field8;
    }

    public void setField8(String value) {
        field8 = value;
    }
    public String getField9() {
        return field9;
    }

    public void setField9(String value) {
        field9 = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }

    @JsonProperty("bean_id")
    private String beanId;
  
    @JsonProperty("set_num")
    private Integer setNum;
  
    @JsonProperty("field0")
    private String field0;
  
    @JsonProperty("field1")
    private String field1;
  
    @JsonProperty("field2")
    private String field2;
  
    @JsonProperty("field3")
    private String field3;
  
    @JsonProperty("field4")
    private String field4;
  
    @JsonProperty("field5")
    private String field5;
  
    @JsonProperty("field6")
    private String field6;
  
    @JsonProperty("field7")
    private String field7;
  
    @JsonProperty("field8")
    private String field8;
  
    @JsonProperty("field9")
    private String field9;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
}
