/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the document_revisions table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "DocumentRevisions", tablename = "document_revisions")
@JsonRootName(value = "document_revisions")
@JsonIgnoreProperties(ignoreUnknown = true)
public class DocumentRevisions {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getChangeLog() {
        return changeLog;
    }

    public void setChangeLog(String value) {
        changeLog = value;
    }
    public String getDocumentId() {
        return documentId;
    }

    public void setDocumentId(String value) {
        documentId = value;
    }
    public String getDocId() {
        return docId;
    }

    public void setDocId(String value) {
        docId = value;
    }
    public String getDocType() {
        return docType;
    }

    public void setDocType(String value) {
        docType = value;
    }
    public String getDocUrl() {
        return docUrl;
    }

    public void setDocUrl(String value) {
        docUrl = value;
    }
    public Date getDateEntered() {
        return dateEntered;
    }

    public void setDateEntered(Date value) {
        dateEntered = value;
    }
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String value) {
        createdBy = value;
    }
    public String getFilename() {
        return filename;
    }

    public void setFilename(String value) {
        filename = value;
    }
    public String getFileExt() {
        return fileExt;
    }

    public void setFileExt(String value) {
        fileExt = value;
    }
    public String getFileMimeType() {
        return fileMimeType;
    }

    public void setFileMimeType(String value) {
        fileMimeType = value;
    }
    public String getRevision() {
        return revision;
    }

    public void setRevision(String value) {
        revision = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("change_log")
    private String changeLog;
  
    @JsonProperty("document_id")
    private String documentId;
  
    @JsonProperty("doc_id")
    private String docId;
  
    @JsonProperty("doc_type")
    private String docType;
  
    @JsonProperty("doc_url")
    private String docUrl;
  
    @JsonProperty("date_entered")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateEntered;
  
    @JsonProperty("created_by")
    private String createdBy;
  
    @JsonProperty("filename")
    private String filename;
  
    @JsonProperty("file_ext")
    private String fileExt;
  
    @JsonProperty("file_mime_type")
    private String fileMimeType;
  
    @JsonProperty("revision")
    private String revision;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
}
