/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the eapm table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "EAPM", tablename = "eapm")
@JsonRootName(value = "eapm")
@JsonIgnoreProperties(ignoreUnknown = true)
public class EAPM {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getName() {
        return name;
    }

    public void setName(String value) {
        name = value;
    }
    public Date getDateEntered() {
        return dateEntered;
    }

    public void setDateEntered(Date value) {
        dateEntered = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public String getModifiedUserId() {
        return modifiedUserId;
    }

    public void setModifiedUserId(String value) {
        modifiedUserId = value;
    }
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String value) {
        createdBy = value;
    }
    public String getDescription() {
        return description;
    }

    public void setDescription(String value) {
        description = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }
    public String getAssignedUserId() {
        return assignedUserId;
    }

    public void setAssignedUserId(String value) {
        assignedUserId = value;
    }
    public String getPassword() {
        return password;
    }

    public void setPassword(String value) {
        password = value;
    }
    public String getUrl() {
        return url;
    }

    public void setUrl(String value) {
        url = value;
    }
    public String getApplication() {
        return application;
    }

    public void setApplication(String value) {
        application = value;
    }
    public String getApiData() {
        return apiData;
    }

    public void setApiData(String value) {
        apiData = value;
    }
    public String getConsumerKey() {
        return consumerKey;
    }

    public void setConsumerKey(String value) {
        consumerKey = value;
    }
    public String getConsumerSecret() {
        return consumerSecret;
    }

    public void setConsumerSecret(String value) {
        consumerSecret = value;
    }
    public String getOauthToken() {
        return oauthToken;
    }

    public void setOauthToken(String value) {
        oauthToken = value;
    }
    public String getOauthSecret() {
        return oauthSecret;
    }

    public void setOauthSecret(String value) {
        oauthSecret = value;
    }
    public Integer getValidated() {
        return validated;
    }

    public void setValidated(Integer value) {
        validated = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("name")
    private String name;
  
    @JsonProperty("date_entered")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateEntered;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("modified_user_id")
    private String modifiedUserId;
  
    @JsonProperty("created_by")
    private String createdBy;
  
    @JsonProperty("description")
    private String description;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
    @JsonProperty("assigned_user_id")
    private String assignedUserId;
  
    @JsonProperty("password")
    private String password;
  
    @JsonProperty("url")
    private String url;
  
    @JsonProperty("application")
    private String application;
  
    @JsonProperty("api_data")
    private String apiData;
  
    @JsonProperty("consumer_key")
    private String consumerKey;
  
    @JsonProperty("consumer_secret")
    private String consumerSecret;
  
    @JsonProperty("oauth_token")
    private String oauthToken;
  
    @JsonProperty("oauth_secret")
    private String oauthSecret;
  
    @JsonProperty("validated")
    private Integer validated;
  
}
