/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the email_addr_bean_rel table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "", tablename = "email_addr_bean_rel")
@JsonRootName(value = "email_addr_bean_rel")
@JsonIgnoreProperties(ignoreUnknown = true)
public class EmailAddrBeanRel {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getEmailAddressId() {
        return emailAddressId;
    }

    public void setEmailAddressId(String value) {
        emailAddressId = value;
    }
    public String getBeanId() {
        return beanId;
    }

    public void setBeanId(String value) {
        beanId = value;
    }
    public String getBeanModule() {
        return beanModule;
    }

    public void setBeanModule(String value) {
        beanModule = value;
    }
    public Integer getPrimaryAddress() {
        return primaryAddress;
    }

    public void setPrimaryAddress(Integer value) {
        primaryAddress = value;
    }
    public Integer getReplyToAddress() {
        return replyToAddress;
    }

    public void setReplyToAddress(Integer value) {
        replyToAddress = value;
    }
    public Date getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(Date value) {
        dateCreated = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("email_address_id")
    private String emailAddressId;
  
    @JsonProperty("bean_id")
    private String beanId;
  
    @JsonProperty("bean_module")
    private String beanModule;
  
    @JsonProperty("primary_address")
    private Integer primaryAddress;
  
    @JsonProperty("reply_to_address")
    private Integer replyToAddress;
  
    @JsonProperty("date_created")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateCreated;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
}
