/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the emails_beans table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "", tablename = "emails_beans")
@JsonRootName(value = "emails_beans")
@JsonIgnoreProperties(ignoreUnknown = true)
public class EmailsBeans {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String value) {
        emailId = value;
    }
    public String getBeanId() {
        return beanId;
    }

    public void setBeanId(String value) {
        beanId = value;
    }
    public String getBeanModule() {
        return beanModule;
    }

    public void setBeanModule(String value) {
        beanModule = value;
    }
    public String getCampaignData() {
        return campaignData;
    }

    public void setCampaignData(String value) {
        campaignData = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("email_id")
    private String emailId;
  
    @JsonProperty("bean_id")
    private String beanId;
  
    @JsonProperty("bean_module")
    private String beanModule;
  
    @JsonProperty("campaign_data")
    private String campaignData;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
}
