/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the emailman table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "EmailMan", tablename = "emailman")
@JsonRootName(value = "emailman")
@JsonIgnoreProperties(ignoreUnknown = true)
public class EmailMan {
    public Date getDateEntered() {
        return dateEntered;
    }

    public void setDateEntered(Date value) {
        dateEntered = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public String getUserId() {
        return userId;
    }

    public void setUserId(String value) {
        userId = value;
    }
    public int getId() {
        return id;
    }

    public void setId(int value) {
        id = value;
    }
    public String getCampaignId() {
        return campaignId;
    }

    public void setCampaignId(String value) {
        campaignId = value;
    }
    public String getMarketingId() {
        return marketingId;
    }

    public void setMarketingId(String value) {
        marketingId = value;
    }
    public String getListId() {
        return listId;
    }

    public void setListId(String value) {
        listId = value;
    }
    public Date getSendDateTime() {
        return sendDateTime;
    }

    public void setSendDateTime(Date value) {
        sendDateTime = value;
    }
    public String getModifiedUserId() {
        return modifiedUserId;
    }

    public void setModifiedUserId(String value) {
        modifiedUserId = value;
    }
    public Integer getInQueue() {
        return inQueue;
    }

    public void setInQueue(Integer value) {
        inQueue = value;
    }
    public Date getInQueueDate() {
        return inQueueDate;
    }

    public void setInQueueDate(Date value) {
        inQueueDate = value;
    }
    public Integer getSendAttempts() {
        return sendAttempts;
    }

    public void setSendAttempts(Integer value) {
        sendAttempts = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }
    public String getRelatedId() {
        return relatedId;
    }

    public void setRelatedId(String value) {
        relatedId = value;
    }
    public String getRelatedType() {
        return relatedType;
    }

    public void setRelatedType(String value) {
        relatedType = value;
    }

    @JsonProperty("date_entered")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateEntered;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("user_id")
    private String userId;
  
    @JsonProperty("id")
    private int id;
  
    @JsonProperty("campaign_id")
    private String campaignId;
  
    @JsonProperty("marketing_id")
    private String marketingId;
  
    @JsonProperty("list_id")
    private String listId;
  
    @JsonProperty("send_date_time")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date sendDateTime;
  
    @JsonProperty("modified_user_id")
    private String modifiedUserId;
  
    @JsonProperty("in_queue")
    private Integer inQueue;
  
    @JsonProperty("in_queue_date")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date inQueueDate;
  
    @JsonProperty("send_attempts")
    private Integer sendAttempts;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
    @JsonProperty("related_id")
    private String relatedId;
  
    @JsonProperty("related_type")
    private String relatedType;
  
}
