/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the email_addresses table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "EmailAddresses", tablename = "email_addresses")
@JsonRootName(value = "email_addresses")
@JsonIgnoreProperties(ignoreUnknown = true)
public class EmailAddresses {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getEmailAddress() {
        return emailAddress;
    }

    public void setEmailAddress(String value) {
        emailAddress = value;
    }
    public String getEmailAddressCaps() {
        return emailAddressCaps;
    }

    public void setEmailAddressCaps(String value) {
        emailAddressCaps = value;
    }
    public Integer getInvalidEmail() {
        return invalidEmail;
    }

    public void setInvalidEmail(Integer value) {
        invalidEmail = value;
    }
    public Integer getOptOut() {
        return optOut;
    }

    public void setOptOut(Integer value) {
        optOut = value;
    }
    public Date getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(Date value) {
        dateCreated = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("email_address")
    private String emailAddress;
  
    @JsonProperty("email_address_caps")
    private String emailAddressCaps;
  
    @JsonProperty("invalid_email")
    private Integer invalidEmail;
  
    @JsonProperty("opt_out")
    private Integer optOut;
  
    @JsonProperty("date_created")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateCreated;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
}
