/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the email_cache table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "", tablename = "email_cache")
@JsonRootName(value = "email_cache")
@JsonIgnoreProperties(ignoreUnknown = true)
public class EmailCache {
    public String getIeId() {
        return ieId;
    }

    public void setIeId(String value) {
        ieId = value;
    }
    public String getMbox() {
        return mbox;
    }

    public void setMbox(String value) {
        mbox = value;
    }
    public String getSubject() {
        return subject;
    }

    public void setSubject(String value) {
        subject = value;
    }
    public String getFromaddr() {
        return fromaddr;
    }

    public void setFromaddr(String value) {
        fromaddr = value;
    }
    public String getToaddr() {
        return toaddr;
    }

    public void setToaddr(String value) {
        toaddr = value;
    }
    public Date getSenddate() {
        return senddate;
    }

    public void setSenddate(Date value) {
        senddate = value;
    }
    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String value) {
        messageId = value;
    }
    public Integer getMailsize() {
        return mailsize;
    }

    public void setMailsize(Integer value) {
        mailsize = value;
    }
    public Integer getImapUid() {
        return imapUid;
    }

    public void setImapUid(Integer value) {
        imapUid = value;
    }
    public Integer getMsgno() {
        return msgno;
    }

    public void setMsgno(Integer value) {
        msgno = value;
    }
    public Integer getRecent() {
        return recent;
    }

    public void setRecent(Integer value) {
        recent = value;
    }
    public Integer getFlagged() {
        return flagged;
    }

    public void setFlagged(Integer value) {
        flagged = value;
    }
    public Integer getAnswered() {
        return answered;
    }

    public void setAnswered(Integer value) {
        answered = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }
    public Integer getSeen() {
        return seen;
    }

    public void setSeen(Integer value) {
        seen = value;
    }
    public Integer getDraft() {
        return draft;
    }

    public void setDraft(Integer value) {
        draft = value;
    }

    @JsonProperty("ie_id")
    private String ieId;
  
    @JsonProperty("mbox")
    private String mbox;
  
    @JsonProperty("subject")
    private String subject;
  
    @JsonProperty("fromaddr")
    private String fromaddr;
  
    @JsonProperty("toaddr")
    private String toaddr;
  
    @JsonProperty("senddate")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date senddate;
  
    @JsonProperty("message_id")
    private String messageId;
  
    @JsonProperty("mailsize")
    private Integer mailsize;
  
    @JsonProperty("imap_uid")
    private Integer imapUid;
  
    @JsonProperty("msgno")
    private Integer msgno;
  
    @JsonProperty("recent")
    private Integer recent;
  
    @JsonProperty("flagged")
    private Integer flagged;
  
    @JsonProperty("answered")
    private Integer answered;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
    @JsonProperty("seen")
    private Integer seen;
  
    @JsonProperty("draft")
    private Integer draft;
  
}
