/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the emails_text table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;


@Module(name = "", tablename = "emails_text")
@JsonRootName(value = "emails_text")
@JsonIgnoreProperties(ignoreUnknown = true)
public class EmailsText {
    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String value) {
        emailId = value;
    }
    public String getFromAddr() {
        return fromAddr;
    }

    public void setFromAddr(String value) {
        fromAddr = value;
    }
    public String getReplyToAddr() {
        return replyToAddr;
    }

    public void setReplyToAddr(String value) {
        replyToAddr = value;
    }
    public String getToAddrs() {
        return toAddrs;
    }

    public void setToAddrs(String value) {
        toAddrs = value;
    }
    public String getCcAddrs() {
        return ccAddrs;
    }

    public void setCcAddrs(String value) {
        ccAddrs = value;
    }
    public String getBccAddrs() {
        return bccAddrs;
    }

    public void setBccAddrs(String value) {
        bccAddrs = value;
    }
    public String getDescription() {
        return description;
    }

    public void setDescription(String value) {
        description = value;
    }
    public String getDescriptionHtml() {
        return descriptionHtml;
    }

    public void setDescriptionHtml(String value) {
        descriptionHtml = value;
    }
    public String getRawSource() {
        return rawSource;
    }

    public void setRawSource(String value) {
        rawSource = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }

    @JsonProperty("email_id")
    private String emailId;
  
    @JsonProperty("from_addr")
    private String fromAddr;
  
    @JsonProperty("reply_to_addr")
    private String replyToAddr;
  
    @JsonProperty("to_addrs")
    private String toAddrs;
  
    @JsonProperty("cc_addrs")
    private String ccAddrs;
  
    @JsonProperty("bcc_addrs")
    private String bccAddrs;
  
    @JsonProperty("description")
    private String description;
  
    @JsonProperty("description_html")
    private String descriptionHtml;
  
    @JsonProperty("raw_source")
    private String rawSource;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
}
