/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the fields_meta_data table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "", tablename = "fields_meta_data")
@JsonRootName(value = "fields_meta_data")
@JsonIgnoreProperties(ignoreUnknown = true)
public class FieldsMetaData {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getName() {
        return name;
    }

    public void setName(String value) {
        name = value;
    }
    public String getVname() {
        return vname;
    }

    public void setVname(String value) {
        vname = value;
    }
    public String getComments() {
        return comments;
    }

    public void setComments(String value) {
        comments = value;
    }
    public String getHelp() {
        return help;
    }

    public void setHelp(String value) {
        help = value;
    }
    public String getCustomModule() {
        return customModule;
    }

    public void setCustomModule(String value) {
        customModule = value;
    }
    public String getType() {
        return type;
    }

    public void setType(String value) {
        type = value;
    }
    public Integer getLen() {
        return len;
    }

    public void setLen(Integer value) {
        len = value;
    }
    public Integer getRequired() {
        return required;
    }

    public void setRequired(Integer value) {
        required = value;
    }
    public String getDefaultValue() {
        return defaultValue;
    }

    public void setDefaultValue(String value) {
        defaultValue = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }
    public Integer getAudited() {
        return audited;
    }

    public void setAudited(Integer value) {
        audited = value;
    }
    public Integer getMassupdate() {
        return massupdate;
    }

    public void setMassupdate(Integer value) {
        massupdate = value;
    }
    public Integer getDuplicateMerge() {
        return duplicateMerge;
    }

    public void setDuplicateMerge(Integer value) {
        duplicateMerge = value;
    }
    public Integer getReportable() {
        return reportable;
    }

    public void setReportable(Integer value) {
        reportable = value;
    }
    public String getImportable() {
        return importable;
    }

    public void setImportable(String value) {
        importable = value;
    }
    public String getExt1() {
        return ext1;
    }

    public void setExt1(String value) {
        ext1 = value;
    }
    public String getExt2() {
        return ext2;
    }

    public void setExt2(String value) {
        ext2 = value;
    }
    public String getExt3() {
        return ext3;
    }

    public void setExt3(String value) {
        ext3 = value;
    }
    public String getExt4() {
        return ext4;
    }

    public void setExt4(String value) {
        ext4 = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("name")
    private String name;
  
    @JsonProperty("vname")
    private String vname;
  
    @JsonProperty("comments")
    private String comments;
  
    @JsonProperty("help")
    private String help;
  
    @JsonProperty("custom_module")
    private String customModule;
  
    @JsonProperty("type")
    private String type;
  
    @JsonProperty("len")
    private Integer len;
  
    @JsonProperty("required")
    private Integer required;
  
    @JsonProperty("default_value")
    private String defaultValue;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
    @JsonProperty("audited")
    private Integer audited;
  
    @JsonProperty("massupdate")
    private Integer massupdate;
  
    @JsonProperty("duplicate_merge")
    private Integer duplicateMerge;
  
    @JsonProperty("reportable")
    private Integer reportable;
  
    @JsonProperty("importable")
    private String importable;
  
    @JsonProperty("ext1")
    private String ext1;
  
    @JsonProperty("ext2")
    private String ext2;
  
    @JsonProperty("ext3")
    private String ext3;
  
    @JsonProperty("ext4")
    private String ext4;
  
}
