/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the import_maps table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "", tablename = "import_maps")
@JsonRootName(value = "import_maps")
@JsonIgnoreProperties(ignoreUnknown = true)
public class ImportMaps {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getName() {
        return name;
    }

    public void setName(String value) {
        name = value;
    }
    public String getSource() {
        return source;
    }

    public void setSource(String value) {
        source = value;
    }
    public String getEnclosure() {
        return enclosure;
    }

    public void setEnclosure(String value) {
        enclosure = value;
    }
    public String getDelimiter() {
        return delimiter;
    }

    public void setDelimiter(String value) {
        delimiter = value;
    }
    public String getModule() {
        return module;
    }

    public void setModule(String value) {
        module = value;
    }
    public String getContent() {
        return content;
    }

    public void setContent(String value) {
        content = value;
    }
    public String getDefaultValues() {
        return defaultValues;
    }

    public void setDefaultValues(String value) {
        defaultValues = value;
    }
    public Integer getHasHeader() {
        return hasHeader;
    }

    public void setHasHeader(Integer value) {
        hasHeader = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }
    public Date getDateEntered() {
        return dateEntered;
    }

    public void setDateEntered(Date value) {
        dateEntered = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public String getAssignedUserId() {
        return assignedUserId;
    }

    public void setAssignedUserId(String value) {
        assignedUserId = value;
    }
    public String getIsPublished() {
        return isPublished;
    }

    public void setIsPublished(String value) {
        isPublished = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("name")
    private String name;
  
    @JsonProperty("source")
    private String source;
  
    @JsonProperty("enclosure")
    private String enclosure;
  
    @JsonProperty("delimiter")
    private String delimiter;
  
    @JsonProperty("module")
    private String module;
  
    @JsonProperty("content")
    private String content;
  
    @JsonProperty("default_values")
    private String defaultValues;
  
    @JsonProperty("has_header")
    private Integer hasHeader;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
    @JsonProperty("date_entered")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateEntered;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("assigned_user_id")
    private String assignedUserId;
  
    @JsonProperty("is_published")
    private String isPublished;
  
}
