/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the inbound_email table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "InboundEmail", tablename = "inbound_email")
@JsonRootName(value = "inbound_email")
@JsonIgnoreProperties(ignoreUnknown = true)
public class InboundEmail {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }
    public Date getDateEntered() {
        return dateEntered;
    }

    public void setDateEntered(Date value) {
        dateEntered = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public String getModifiedUserId() {
        return modifiedUserId;
    }

    public void setModifiedUserId(String value) {
        modifiedUserId = value;
    }
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String value) {
        createdBy = value;
    }
    public String getName() {
        return name;
    }

    public void setName(String value) {
        name = value;
    }
    public String getStatus() {
        return status;
    }

    public void setStatus(String value) {
        status = value;
    }
    public String getServerUrl() {
        return serverUrl;
    }

    public void setServerUrl(String value) {
        serverUrl = value;
    }
    public String getEmailUser() {
        return emailUser;
    }

    public void setEmailUser(String value) {
        emailUser = value;
    }
    public String getEmailPassword() {
        return emailPassword;
    }

    public void setEmailPassword(String value) {
        emailPassword = value;
    }
    public Integer getPort() {
        return port;
    }

    public void setPort(Integer value) {
        port = value;
    }
    public String getService() {
        return service;
    }

    public void setService(String value) {
        service = value;
    }
    public String getMailbox() {
        return mailbox;
    }

    public void setMailbox(String value) {
        mailbox = value;
    }
    public Integer getDeleteSeen() {
        return deleteSeen;
    }

    public void setDeleteSeen(Integer value) {
        deleteSeen = value;
    }
    public String getMailboxType() {
        return mailboxType;
    }

    public void setMailboxType(String value) {
        mailboxType = value;
    }
    public String getTemplateId() {
        return templateId;
    }

    public void setTemplateId(String value) {
        templateId = value;
    }
    public String getStoredOptions() {
        return storedOptions;
    }

    public void setStoredOptions(String value) {
        storedOptions = value;
    }
    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String value) {
        groupId = value;
    }
    public Integer getIsPersonal() {
        return isPersonal;
    }

    public void setIsPersonal(Integer value) {
        isPersonal = value;
    }
    public String getGroupfolderId() {
        return groupfolderId;
    }

    public void setGroupfolderId(String value) {
        groupfolderId = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
    @JsonProperty("date_entered")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateEntered;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("modified_user_id")
    private String modifiedUserId;
  
    @JsonProperty("created_by")
    private String createdBy;
  
    @JsonProperty("name")
    private String name;
  
    @JsonProperty("status")
    private String status;
  
    @JsonProperty("server_url")
    private String serverUrl;
  
    @JsonProperty("email_user")
    private String emailUser;
  
    @JsonProperty("email_password")
    private String emailPassword;
  
    @JsonProperty("port")
    private Integer port;
  
    @JsonProperty("service")
    private String service;
  
    @JsonProperty("mailbox")
    private String mailbox;
  
    @JsonProperty("delete_seen")
    private Integer deleteSeen;
  
    @JsonProperty("mailbox_type")
    private String mailboxType;
  
    @JsonProperty("template_id")
    private String templateId;
  
    @JsonProperty("stored_options")
    private String storedOptions;
  
    @JsonProperty("group_id")
    private String groupId;
  
    @JsonProperty("is_personal")
    private Integer isPersonal;
  
    @JsonProperty("groupfolder_id")
    private String groupfolderId;
  
}
