/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the oauth_tokens table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;


@Module(name = "OAuthTokens", tablename = "oauth_tokens")
@JsonRootName(value = "oauth_tokens")
@JsonIgnoreProperties(ignoreUnknown = true)
public class OAuthTokens {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getSecret() {
        return secret;
    }

    public void setSecret(String value) {
        secret = value;
    }
    public String getTstate() {
        return tstate;
    }

    public void setTstate(String value) {
        tstate = value;
    }
    public String getConsumer() {
        return consumer;
    }

    public void setConsumer(String value) {
        consumer = value;
    }
    public Long getTokenTs() {
        return tokenTs;
    }

    public void setTokenTs(Long value) {
        tokenTs = value;
    }
    public String getVerify() {
        return verify;
    }

    public void setVerify(String value) {
        verify = value;
    }
    public int getDeleted() {
        return deleted;
    }

    public void setDeleted(int value) {
        deleted = value;
    }
    public String getCallbackUrl() {
        return callbackUrl;
    }

    public void setCallbackUrl(String value) {
        callbackUrl = value;
    }
    public String getAssignedUserId() {
        return assignedUserId;
    }

    public void setAssignedUserId(String value) {
        assignedUserId = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("secret")
    private String secret;
  
    @JsonProperty("tstate")
    private String tstate;
  
    @JsonProperty("consumer")
    private String consumer;
  
    @JsonProperty("token_ts")
    private Long tokenTs;
  
    @JsonProperty("verify")
    private String verify;
  
    @JsonProperty("deleted")
    private int deleted;
  
    @JsonProperty("callback_url")
    private String callbackUrl;
  
    @JsonProperty("assigned_user_id")
    private String assignedUserId;
  
}
