/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the oauth_nonce table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;


@Module(name = "", tablename = "oauth_nonce")
@JsonRootName(value = "oauth_nonce")
@JsonIgnoreProperties(ignoreUnknown = true)
public class OauthNonce {
    public String getConskey() {
        return conskey;
    }

    public void setConskey(String value) {
        conskey = value;
    }
    public String getNonce() {
        return nonce;
    }

    public void setNonce(String value) {
        nonce = value;
    }
    public Long getNonceTs() {
        return nonceTs;
    }

    public void setNonceTs(Long value) {
        nonceTs = value;
    }

    @JsonProperty("conskey")
    private String conskey;
  
    @JsonProperty("nonce")
    private String nonce;
  
    @JsonProperty("nonce_ts")
    private Long nonceTs;
  
}
