/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the opportunities table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "Opportunities", tablename = "opportunities")
@JsonRootName(value = "opportunities")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Opportunities {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getName() {
        return name;
    }

    public void setName(String value) {
        name = value;
    }
    public Date getDateEntered() {
        return dateEntered;
    }

    public void setDateEntered(Date value) {
        dateEntered = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public String getModifiedUserId() {
        return modifiedUserId;
    }

    public void setModifiedUserId(String value) {
        modifiedUserId = value;
    }
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String value) {
        createdBy = value;
    }
    public String getDescription() {
        return description;
    }

    public void setDescription(String value) {
        description = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }
    public String getAssignedUserId() {
        return assignedUserId;
    }

    public void setAssignedUserId(String value) {
        assignedUserId = value;
    }
    public String getOpportunityType() {
        return opportunityType;
    }

    public void setOpportunityType(String value) {
        opportunityType = value;
    }
    public String getCampaignId() {
        return campaignId;
    }

    public void setCampaignId(String value) {
        campaignId = value;
    }
    public String getLeadSource() {
        return leadSource;
    }

    public void setLeadSource(String value) {
        leadSource = value;
    }
    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double value) {
        amount = value;
    }
    public Double getAmountUsdollar() {
        return amountUsdollar;
    }

    public void setAmountUsdollar(Double value) {
        amountUsdollar = value;
    }
    public String getCurrencyId() {
        return currencyId;
    }

    public void setCurrencyId(String value) {
        currencyId = value;
    }
    public Date getDateClosed() {
        return dateClosed;
    }

    public void setDateClosed(Date value) {
        dateClosed = value;
    }
    public String getNextStep() {
        return nextStep;
    }

    public void setNextStep(String value) {
        nextStep = value;
    }
    public String getSalesStage() {
        return salesStage;
    }

    public void setSalesStage(String value) {
        salesStage = value;
    }
    public Double getProbability() {
        return probability;
    }

    public void setProbability(Double value) {
        probability = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("name")
    private String name;
  
    @JsonProperty("date_entered")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateEntered;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("modified_user_id")
    private String modifiedUserId;
  
    @JsonProperty("created_by")
    private String createdBy;
  
    @JsonProperty("description")
    private String description;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
    @JsonProperty("assigned_user_id")
    private String assignedUserId;
  
    @JsonProperty("opportunity_type")
    private String opportunityType;
  
    @JsonProperty("campaign_id")
    private String campaignId;
  
    @JsonProperty("lead_source")
    private String leadSource;
  
    @JsonProperty("amount")
    private Double amount;
  
    @JsonProperty("amount_usdollar")
    private Double amountUsdollar;
  
    @JsonProperty("currency_id")
    private String currencyId;
  
    @JsonProperty("date_closed")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateClosed;
  
    @JsonProperty("next_step")
    private String nextStep;
  
    @JsonProperty("sales_stage")
    private String salesStage;
  
    @JsonProperty("probability")
    private Double probability;
  
}
