/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the project_task table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "ProjectTask", tablename = "project_task")
@JsonRootName(value = "project_task")
@JsonIgnoreProperties(ignoreUnknown = true)
public class ProjectTask {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public Date getDateEntered() {
        return dateEntered;
    }

    public void setDateEntered(Date value) {
        dateEntered = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String value) {
        projectId = value;
    }
    public Integer getProjectTaskId() {
        return projectTaskId;
    }

    public void setProjectTaskId(Integer value) {
        projectTaskId = value;
    }
    public String getName() {
        return name;
    }

    public void setName(String value) {
        name = value;
    }
    public String getStatus() {
        return status;
    }

    public void setStatus(String value) {
        status = value;
    }
    public String getDescription() {
        return description;
    }

    public void setDescription(String value) {
        description = value;
    }
    public String getPredecessors() {
        return predecessors;
    }

    public void setPredecessors(String value) {
        predecessors = value;
    }
    public Date getDateStart() {
        return dateStart;
    }

    public void setDateStart(Date value) {
        dateStart = value;
    }
    public Integer getTimeStart() {
        return timeStart;
    }

    public void setTimeStart(Integer value) {
        timeStart = value;
    }
    public Integer getTimeFinish() {
        return timeFinish;
    }

    public void setTimeFinish(Integer value) {
        timeFinish = value;
    }
    public Date getDateFinish() {
        return dateFinish;
    }

    public void setDateFinish(Date value) {
        dateFinish = value;
    }
    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer value) {
        duration = value;
    }
    public String getDurationUnit() {
        return durationUnit;
    }

    public void setDurationUnit(String value) {
        durationUnit = value;
    }
    public Integer getActualDuration() {
        return actualDuration;
    }

    public void setActualDuration(Integer value) {
        actualDuration = value;
    }
    public Integer getPercentComplete() {
        return percentComplete;
    }

    public void setPercentComplete(Integer value) {
        percentComplete = value;
    }
    public Date getDateDue() {
        return dateDue;
    }

    public void setDateDue(Date value) {
        dateDue = value;
    }
    public Date getTimeDue() {
        return timeDue;
    }

    public void setTimeDue(Date value) {
        timeDue = value;
    }
    public Integer getParentTaskId() {
        return parentTaskId;
    }

    public void setParentTaskId(Integer value) {
        parentTaskId = value;
    }
    public String getAssignedUserId() {
        return assignedUserId;
    }

    public void setAssignedUserId(String value) {
        assignedUserId = value;
    }
    public String getModifiedUserId() {
        return modifiedUserId;
    }

    public void setModifiedUserId(String value) {
        modifiedUserId = value;
    }
    public String getPriority() {
        return priority;
    }

    public void setPriority(String value) {
        priority = value;
    }
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String value) {
        createdBy = value;
    }
    public Integer getMilestoneFlag() {
        return milestoneFlag;
    }

    public void setMilestoneFlag(Integer value) {
        milestoneFlag = value;
    }
    public Integer getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(Integer value) {
        orderNumber = value;
    }
    public Integer getTaskNumber() {
        return taskNumber;
    }

    public void setTaskNumber(Integer value) {
        taskNumber = value;
    }
    public Integer getEstimatedEffort() {
        return estimatedEffort;
    }

    public void setEstimatedEffort(Integer value) {
        estimatedEffort = value;
    }
    public Integer getActualEffort() {
        return actualEffort;
    }

    public void setActualEffort(Integer value) {
        actualEffort = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }
    public Integer getUtilization() {
        return utilization;
    }

    public void setUtilization(Integer value) {
        utilization = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("date_entered")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateEntered;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("project_id")
    private String projectId;
  
    @JsonProperty("project_task_id")
    private Integer projectTaskId;
  
    @JsonProperty("name")
    private String name;
  
    @JsonProperty("status")
    private String status;
  
    @JsonProperty("description")
    private String description;
  
    @JsonProperty("predecessors")
    private String predecessors;
  
    @JsonProperty("date_start")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateStart;
  
    @JsonProperty("time_start")
    private Integer timeStart;
  
    @JsonProperty("time_finish")
    private Integer timeFinish;
  
    @JsonProperty("date_finish")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateFinish;
  
    @JsonProperty("duration")
    private Integer duration;
  
    @JsonProperty("duration_unit")
    private String durationUnit;
  
    @JsonProperty("actual_duration")
    private Integer actualDuration;
  
    @JsonProperty("percent_complete")
    private Integer percentComplete;
  
    @JsonProperty("date_due")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateDue;
  
    @JsonProperty("time_due")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date timeDue;
  
    @JsonProperty("parent_task_id")
    private Integer parentTaskId;
  
    @JsonProperty("assigned_user_id")
    private String assignedUserId;
  
    @JsonProperty("modified_user_id")
    private String modifiedUserId;
  
    @JsonProperty("priority")
    private String priority;
  
    @JsonProperty("created_by")
    private String createdBy;
  
    @JsonProperty("milestone_flag")
    private Integer milestoneFlag;
  
    @JsonProperty("order_number")
    private Integer orderNumber;
  
    @JsonProperty("task_number")
    private Integer taskNumber;
  
    @JsonProperty("estimated_effort")
    private Integer estimatedEffort;
  
    @JsonProperty("actual_effort")
    private Integer actualEffort;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
    @JsonProperty("utilization")
    private Integer utilization;
  
}
