/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the prospects table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "Prospects", tablename = "prospects")
@JsonRootName(value = "prospects")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Prospects {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public Date getDateEntered() {
        return dateEntered;
    }

    public void setDateEntered(Date value) {
        dateEntered = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public String getModifiedUserId() {
        return modifiedUserId;
    }

    public void setModifiedUserId(String value) {
        modifiedUserId = value;
    }
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String value) {
        createdBy = value;
    }
    public String getDescription() {
        return description;
    }

    public void setDescription(String value) {
        description = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }
    public String getAssignedUserId() {
        return assignedUserId;
    }

    public void setAssignedUserId(String value) {
        assignedUserId = value;
    }
    public String getSalutation() {
        return salutation;
    }

    public void setSalutation(String value) {
        salutation = value;
    }
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String value) {
        firstName = value;
    }
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String value) {
        lastName = value;
    }
    public String getTitle() {
        return title;
    }

    public void setTitle(String value) {
        title = value;
    }
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String value) {
        department = value;
    }
    public Integer getDoNotCall() {
        return doNotCall;
    }

    public void setDoNotCall(Integer value) {
        doNotCall = value;
    }
    public String getPhoneHome() {
        return phoneHome;
    }

    public void setPhoneHome(String value) {
        phoneHome = value;
    }
    public String getPhoneMobile() {
        return phoneMobile;
    }

    public void setPhoneMobile(String value) {
        phoneMobile = value;
    }
    public String getPhoneWork() {
        return phoneWork;
    }

    public void setPhoneWork(String value) {
        phoneWork = value;
    }
    public String getPhoneOther() {
        return phoneOther;
    }

    public void setPhoneOther(String value) {
        phoneOther = value;
    }
    public String getPhoneFax() {
        return phoneFax;
    }

    public void setPhoneFax(String value) {
        phoneFax = value;
    }
    public String getPrimaryAddressStreet() {
        return primaryAddressStreet;
    }

    public void setPrimaryAddressStreet(String value) {
        primaryAddressStreet = value;
    }
    public String getPrimaryAddressCity() {
        return primaryAddressCity;
    }

    public void setPrimaryAddressCity(String value) {
        primaryAddressCity = value;
    }
    public String getPrimaryAddressState() {
        return primaryAddressState;
    }

    public void setPrimaryAddressState(String value) {
        primaryAddressState = value;
    }
    public String getPrimaryAddressPostalcode() {
        return primaryAddressPostalcode;
    }

    public void setPrimaryAddressPostalcode(String value) {
        primaryAddressPostalcode = value;
    }
    public String getPrimaryAddressCountry() {
        return primaryAddressCountry;
    }

    public void setPrimaryAddressCountry(String value) {
        primaryAddressCountry = value;
    }
    public String getAltAddressStreet() {
        return altAddressStreet;
    }

    public void setAltAddressStreet(String value) {
        altAddressStreet = value;
    }
    public String getAltAddressCity() {
        return altAddressCity;
    }

    public void setAltAddressCity(String value) {
        altAddressCity = value;
    }
    public String getAltAddressState() {
        return altAddressState;
    }

    public void setAltAddressState(String value) {
        altAddressState = value;
    }
    public String getAltAddressPostalcode() {
        return altAddressPostalcode;
    }

    public void setAltAddressPostalcode(String value) {
        altAddressPostalcode = value;
    }
    public String getAltAddressCountry() {
        return altAddressCountry;
    }

    public void setAltAddressCountry(String value) {
        altAddressCountry = value;
    }
    public String getAssistant() {
        return assistant;
    }

    public void setAssistant(String value) {
        assistant = value;
    }
    public String getAssistantPhone() {
        return assistantPhone;
    }

    public void setAssistantPhone(String value) {
        assistantPhone = value;
    }
    public int getTrackerKey() {
        return trackerKey;
    }

    public void setTrackerKey(int value) {
        trackerKey = value;
    }
    public Date getBirthdate() {
        return birthdate;
    }

    public void setBirthdate(Date value) {
        birthdate = value;
    }
    public String getLeadId() {
        return leadId;
    }

    public void setLeadId(String value) {
        leadId = value;
    }
    public String getAccountName() {
        return accountName;
    }

    public void setAccountName(String value) {
        accountName = value;
    }
    public String getCampaignId() {
        return campaignId;
    }

    public void setCampaignId(String value) {
        campaignId = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("date_entered")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateEntered;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("modified_user_id")
    private String modifiedUserId;
  
    @JsonProperty("created_by")
    private String createdBy;
  
    @JsonProperty("description")
    private String description;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
    @JsonProperty("assigned_user_id")
    private String assignedUserId;
  
    @JsonProperty("salutation")
    private String salutation;
  
    @JsonProperty("first_name")
    private String firstName;
  
    @JsonProperty("last_name")
    private String lastName;
  
    @JsonProperty("title")
    private String title;
  
    @JsonProperty("department")
    private String department;
  
    @JsonProperty("do_not_call")
    private Integer doNotCall;
  
    @JsonProperty("phone_home")
    private String phoneHome;
  
    @JsonProperty("phone_mobile")
    private String phoneMobile;
  
    @JsonProperty("phone_work")
    private String phoneWork;
  
    @JsonProperty("phone_other")
    private String phoneOther;
  
    @JsonProperty("phone_fax")
    private String phoneFax;
  
    @JsonProperty("primary_address_street")
    private String primaryAddressStreet;
  
    @JsonProperty("primary_address_city")
    private String primaryAddressCity;
  
    @JsonProperty("primary_address_state")
    private String primaryAddressState;
  
    @JsonProperty("primary_address_postalcode")
    private String primaryAddressPostalcode;
  
    @JsonProperty("primary_address_country")
    private String primaryAddressCountry;
  
    @JsonProperty("alt_address_street")
    private String altAddressStreet;
  
    @JsonProperty("alt_address_city")
    private String altAddressCity;
  
    @JsonProperty("alt_address_state")
    private String altAddressState;
  
    @JsonProperty("alt_address_postalcode")
    private String altAddressPostalcode;
  
    @JsonProperty("alt_address_country")
    private String altAddressCountry;
  
    @JsonProperty("assistant")
    private String assistant;
  
    @JsonProperty("assistant_phone")
    private String assistantPhone;
  
    @JsonProperty("tracker_key")
    private int trackerKey;
  
    @JsonProperty("birthdate")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date birthdate;
  
    @JsonProperty("lead_id")
    private String leadId;
  
    @JsonProperty("account_name")
    private String accountName;
  
    @JsonProperty("campaign_id")
    private String campaignId;
  
}
