/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the relationships table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;


@Module(name = "", tablename = "relationships")
@JsonRootName(value = "relationships")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Relationships {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getRelationshipName() {
        return relationshipName;
    }

    public void setRelationshipName(String value) {
        relationshipName = value;
    }
    public String getLhsModule() {
        return lhsModule;
    }

    public void setLhsModule(String value) {
        lhsModule = value;
    }
    public String getLhsTable() {
        return lhsTable;
    }

    public void setLhsTable(String value) {
        lhsTable = value;
    }
    public String getLhsKey() {
        return lhsKey;
    }

    public void setLhsKey(String value) {
        lhsKey = value;
    }
    public String getRhsModule() {
        return rhsModule;
    }

    public void setRhsModule(String value) {
        rhsModule = value;
    }
    public String getRhsTable() {
        return rhsTable;
    }

    public void setRhsTable(String value) {
        rhsTable = value;
    }
    public String getRhsKey() {
        return rhsKey;
    }

    public void setRhsKey(String value) {
        rhsKey = value;
    }
    public String getJoinTable() {
        return joinTable;
    }

    public void setJoinTable(String value) {
        joinTable = value;
    }
    public String getJoinKeyLhs() {
        return joinKeyLhs;
    }

    public void setJoinKeyLhs(String value) {
        joinKeyLhs = value;
    }
    public String getJoinKeyRhs() {
        return joinKeyRhs;
    }

    public void setJoinKeyRhs(String value) {
        joinKeyRhs = value;
    }
    public String getRelationshipType() {
        return relationshipType;
    }

    public void setRelationshipType(String value) {
        relationshipType = value;
    }
    public String getRelationshipRoleColumn() {
        return relationshipRoleColumn;
    }

    public void setRelationshipRoleColumn(String value) {
        relationshipRoleColumn = value;
    }
    public String getRelationshipRoleColumnValue() {
        return relationshipRoleColumnValue;
    }

    public void setRelationshipRoleColumnValue(String value) {
        relationshipRoleColumnValue = value;
    }
    public Integer getReverse() {
        return reverse;
    }

    public void setReverse(Integer value) {
        reverse = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("relationship_name")
    private String relationshipName;
  
    @JsonProperty("lhs_module")
    private String lhsModule;
  
    @JsonProperty("lhs_table")
    private String lhsTable;
  
    @JsonProperty("lhs_key")
    private String lhsKey;
  
    @JsonProperty("rhs_module")
    private String rhsModule;
  
    @JsonProperty("rhs_table")
    private String rhsTable;
  
    @JsonProperty("rhs_key")
    private String rhsKey;
  
    @JsonProperty("join_table")
    private String joinTable;
  
    @JsonProperty("join_key_lhs")
    private String joinKeyLhs;
  
    @JsonProperty("join_key_rhs")
    private String joinKeyRhs;
  
    @JsonProperty("relationship_type")
    private String relationshipType;
  
    @JsonProperty("relationship_role_column")
    private String relationshipRoleColumn;
  
    @JsonProperty("relationship_role_column_value")
    private String relationshipRoleColumnValue;
  
    @JsonProperty("reverse")
    private Integer reverse;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
}
