/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the schedulers table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "Schedulers", tablename = "schedulers")
@JsonRootName(value = "schedulers")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Schedulers {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }
    public Date getDateEntered() {
        return dateEntered;
    }

    public void setDateEntered(Date value) {
        dateEntered = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String value) {
        createdBy = value;
    }
    public String getModifiedUserId() {
        return modifiedUserId;
    }

    public void setModifiedUserId(String value) {
        modifiedUserId = value;
    }
    public String getName() {
        return name;
    }

    public void setName(String value) {
        name = value;
    }
    public String getJob() {
        return job;
    }

    public void setJob(String value) {
        job = value;
    }
    public Date getDateTimeStart() {
        return dateTimeStart;
    }

    public void setDateTimeStart(Date value) {
        dateTimeStart = value;
    }
    public Date getDateTimeEnd() {
        return dateTimeEnd;
    }

    public void setDateTimeEnd(Date value) {
        dateTimeEnd = value;
    }
    public String getJobInterval() {
        return jobInterval;
    }

    public void setJobInterval(String value) {
        jobInterval = value;
    }
    public Date getTimeFrom() {
        return timeFrom;
    }

    public void setTimeFrom(Date value) {
        timeFrom = value;
    }
    public Date getTimeTo() {
        return timeTo;
    }

    public void setTimeTo(Date value) {
        timeTo = value;
    }
    public Date getLastRun() {
        return lastRun;
    }

    public void setLastRun(Date value) {
        lastRun = value;
    }
    public String getStatus() {
        return status;
    }

    public void setStatus(String value) {
        status = value;
    }
    public Integer getCatchUp() {
        return catchUp;
    }

    public void setCatchUp(Integer value) {
        catchUp = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
    @JsonProperty("date_entered")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateEntered;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("created_by")
    private String createdBy;
  
    @JsonProperty("modified_user_id")
    private String modifiedUserId;
  
    @JsonProperty("name")
    private String name;
  
    @JsonProperty("job")
    private String job;
  
    @JsonProperty("date_time_start")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateTimeStart;
  
    @JsonProperty("date_time_end")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateTimeEnd;
  
    @JsonProperty("job_interval")
    private String jobInterval;
  
    @JsonProperty("time_from")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date timeFrom;
  
    @JsonProperty("time_to")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date timeTo;
  
    @JsonProperty("last_run")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date lastRun;
  
    @JsonProperty("status")
    private String status;
  
    @JsonProperty("catch_up")
    private Integer catchUp;
  
}
