/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the job_queue table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "SchedulersJobs", tablename = "job_queue")
@JsonRootName(value = "job_queue")
@JsonIgnoreProperties(ignoreUnknown = true)
public class SchedulersJobs {
    public String getAssignedUserId() {
        return assignedUserId;
    }

    public void setAssignedUserId(String value) {
        assignedUserId = value;
    }
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getName() {
        return name;
    }

    public void setName(String value) {
        name = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }
    public Date getDateEntered() {
        return dateEntered;
    }

    public void setDateEntered(Date value) {
        dateEntered = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public String getSchedulerId() {
        return schedulerId;
    }

    public void setSchedulerId(String value) {
        schedulerId = value;
    }
    public Date getExecuteTime() {
        return executeTime;
    }

    public void setExecuteTime(Date value) {
        executeTime = value;
    }
    public String getStatus() {
        return status;
    }

    public void setStatus(String value) {
        status = value;
    }
    public String getResolution() {
        return resolution;
    }

    public void setResolution(String value) {
        resolution = value;
    }
    public String getMessage() {
        return message;
    }

    public void setMessage(String value) {
        message = value;
    }
    public String getTarget() {
        return target;
    }

    public void setTarget(String value) {
        target = value;
    }
    public String getData() {
        return data;
    }

    public void setData(String value) {
        data = value;
    }
    public Integer getRequeue() {
        return requeue;
    }

    public void setRequeue(Integer value) {
        requeue = value;
    }
    public Integer getRetryCount() {
        return retryCount;
    }

    public void setRetryCount(Integer value) {
        retryCount = value;
    }
    public Integer getFailureCount() {
        return failureCount;
    }

    public void setFailureCount(Integer value) {
        failureCount = value;
    }
    public Integer getJobDelay() {
        return jobDelay;
    }

    public void setJobDelay(Integer value) {
        jobDelay = value;
    }
    public String getClient() {
        return client;
    }

    public void setClient(String value) {
        client = value;
    }
    public Integer getPercentComplete() {
        return percentComplete;
    }

    public void setPercentComplete(Integer value) {
        percentComplete = value;
    }

    @JsonProperty("assigned_user_id")
    private String assignedUserId;
  
    @JsonProperty("id")
    private String id;
  
    @JsonProperty("name")
    private String name;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
    @JsonProperty("date_entered")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateEntered;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("scheduler_id")
    private String schedulerId;
  
    @JsonProperty("execute_time")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date executeTime;
  
    @JsonProperty("status")
    private String status;
  
    @JsonProperty("resolution")
    private String resolution;
  
    @JsonProperty("message")
    private String message;
  
    @JsonProperty("target")
    private String target;
  
    @JsonProperty("data")
    private String data;
  
    @JsonProperty("requeue")
    private Integer requeue;
  
    @JsonProperty("retry_count")
    private Integer retryCount;
  
    @JsonProperty("failure_count")
    private Integer failureCount;
  
    @JsonProperty("job_delay")
    private Integer jobDelay;
  
    @JsonProperty("client")
    private String client;
  
    @JsonProperty("percent_complete")
    private Integer percentComplete;
  
}
