/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the tracker table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "", tablename = "tracker")
@JsonRootName(value = "tracker")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Tracker {
    public int getId() {
        return id;
    }

    public void setId(int value) {
        id = value;
    }
    public String getMonitorId() {
        return monitorId;
    }

    public void setMonitorId(String value) {
        monitorId = value;
    }
    public String getUserId() {
        return userId;
    }

    public void setUserId(String value) {
        userId = value;
    }
    public String getModuleName() {
        return moduleName;
    }

    public void setModuleName(String value) {
        moduleName = value;
    }
    public String getItemId() {
        return itemId;
    }

    public void setItemId(String value) {
        itemId = value;
    }
    public String getItemSummary() {
        return itemSummary;
    }

    public void setItemSummary(String value) {
        itemSummary = value;
    }
    public Date getDateModified() {
        return dateModified;
    }

    public void setDateModified(Date value) {
        dateModified = value;
    }
    public String getAction() {
        return action;
    }

    public void setAction(String value) {
        action = value;
    }
    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String value) {
        sessionId = value;
    }
    public Integer getVisible() {
        return visible;
    }

    public void setVisible(Integer value) {
        visible = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }

    @JsonProperty("id")
    private int id;
  
    @JsonProperty("monitor_id")
    private String monitorId;
  
    @JsonProperty("user_id")
    private String userId;
  
    @JsonProperty("module_name")
    private String moduleName;
  
    @JsonProperty("item_id")
    private String itemId;
  
    @JsonProperty("item_summary")
    private String itemSummary;
  
    @JsonProperty("date_modified")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateModified;
  
    @JsonProperty("action")
    private String action;
  
    @JsonProperty("session_id")
    private String sessionId;
  
    @JsonProperty("visible")
    private Integer visible;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
}
