/**
* <auto-generated />
* This file was generated by a StringTemplate 4 template.
* Don't change it directly as your change would get overwritten. Instead, make changes
* to the .stg file (i.e. the StringTemplate 4 template file) and save it to regenerate this file.
*
* For more infor on StringTemplate 4 template please go to -
* https://github.com/antlr/antlrcs
*
* @author  Kola Oyewumi
* @version 1.0.0
* @since   2017-01-03
*
* A class which represents the users_password_link table.
*/

package com.sugaronrest.modules;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sugaronrest.restapicalls.Module;
import com.sugaronrest.restapicalls.CustomDateDeserializer;
import com.sugaronrest.restapicalls.CustomDateSerializer;

import java.util.Date;

@Module(name = "", tablename = "users_password_link")
@JsonRootName(value = "users_password_link")
@JsonIgnoreProperties(ignoreUnknown = true)
public class UsersPasswordLink {
    public String getId() {
        return id;
    }

    public void setId(String value) {
        id = value;
    }
    public String getUsername() {
        return username;
    }

    public void setUsername(String value) {
        username = value;
    }
    public Date getDateGenerated() {
        return dateGenerated;
    }

    public void setDateGenerated(Date value) {
        dateGenerated = value;
    }
    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer value) {
        deleted = value;
    }

    @JsonProperty("id")
    private String id;
  
    @JsonProperty("username")
    private String username;
  
    @JsonProperty("date_generated")
    @JsonDeserialize(using = CustomDateDeserializer.class)
    @JsonSerialize(using = CustomDateSerializer.class)
    private Date dateGenerated;
  
    @JsonProperty("deleted")
    private Integer deleted;
  
}
